// src/sb1_tables.hpp
#pragma once
#include <map>
#include <string>

namespace sb {

inline const std::map<std::string, std::string> SB1_BLOCKS = {
    {"EventHatMorph", "当…"},
    {"Scratch-StartClicked", "当 绿旗 被点击"},
    {"whenGreenFlag", "当 绿旗 被点击"},
    {"KeyEventHatMorph", "当按下 ? 键"},
    {"MouseClickEventHatMorph", "当角色被点击"},
    {"whenIReceive", "当接收到 {1}"},
    {"whenSceneStarts", "当背景换成 {1}"},
    {"whenSensorGreaterThan", "当 {1} > {2}"},
    {"forward:", "移动 {1} 步"},
    {"turnRight:", "右转 {1} 度"},
    {"turnLeft:", "左转 {1} 度"},
    {"heading:", "面向 {1} 方向"},
    {"pointTowards:", "面向 {1} 方向"},
    {"gotoX:y:", "移到 x: {1} y: {2}"},
    {"gotoSpriteOrMouse:", "移到 {1}"},
    {"glideSecs:toX:y:elapsed:from:", "在 {1} 秒内滑行到 x: {2} y: {3}"},
    {"changeXposBy:", "将 x 坐标增加 {1}"},
    {"xpos:", "将 x 坐标设为 {1}"},
    {"changeYposBy:", "将 y 坐标增加 {1}"},
    {"ypos:", "将 y 坐标设为 {1}"},
    {"bounceOffEdge", "碰到边缘就反弹"},
    {"setRotationStyle", "将旋转方式设为 {1}"},
    {"say:", "说 {1}"},
    {"say:duration:elapsed:from:", "说 {1} {2} 秒"},
    {"think:", "思考 {1}"},
    {"think:duration:elapsed:from:", "思考 {1} {2} 秒"},
    {"lookLike:", "换成 {1} 造型"},
    {"nextCostume", "下一个造型"},
    {"show", "显示"},
    {"hide", "隐藏"},
    {"comeToFront", "移到最前面"},
    {"goBackByLayers:", "后移 {1} 层"},
    {"changeGraphicEffect:by:", "将 {1} 特效增加 {2}"},
    {"setGraphicEffect:to:", "将 {1} 特效设为 {2}"},
    {"filterReset", "清除图形特效"},
    {"changeSizeBy:", "将大小增加 {1}"},
    {"setSizeTo:", "将大小设为 {1}"},
    {"startScene", "换成 {1} 背景"},
    {"nextScene", "下一个背景"},
    {"playSound:", "播放声音 {1}"},
    {"doPlaySoundAndWait", "播放声音 {1} 等待播完"},
    {"stopAllSounds", "停止所有声音"},
    {"changeVolumeBy:", "将音量增加 {1}"},
    {"setVolumeTo:", "将音量设为 {1}"},
    {"clearPenTrails", "清空画笔"},
    {"putPenDown", "落笔"},
    {"putPenUp", "抬笔"},
    {"stampCostume", "图章"},
    {"penColor:", "将笔的颜色设为 {1}"},
    {"setPenHueTo:", "将笔的色相设为 {1}"},
    {"changePenHueBy:", "将笔的色相增加 {1}"},
    {"setPenShadeTo:", "将笔的明度设为 {1}"},
    {"changePenShadeBy:", "将笔的明度增加 {1}"},
    {"penSize:", "将笔的粗细设为 {1}"},
    {"changePenSizeBy:", "将笔的粗细增加 {1}"},
    {"wait:elapsed:from:", "等待 {1} 秒"},
    {"doForever", "重复执行"},
    {"doRepeat", "重复执行 {1} 次"},
    {"doIf", "如果 {1} 那么"},
    {"doIfElse", "如果 {1} 那么"},
    {"doWaitUntil", "等待直到 {1}"},
    {"doUntil", "重复执行直到 {1}"},
    {"doReturn", "停止这个脚本"},
    {"stopScripts", "停止 {1}"},
    {"createCloneOf", "克隆 {1}"},
    {"deleteClone", "删除此克隆体"},
    {"whenCloned", "当作为克隆体启动时"},
    {"doBroadcastAndWait", "广播 {1} 并等待"},
    {"broadcast:", "广播 {1}"},
    {"+", "({1} + {2})"},
    {"-", "({1} - {2})"},
    {"*", "({1} × {2})"},
    {"/", "({1} ÷ {2})"},
    {"randomFrom:to:", "在 {1} 到 {2} 之间取随机数"},
    {"<", "({1} < {2})"},
    {"=", "({1} = {2})"},
    {">", "({1} > {2})"},
    {"&", "({1} 且 {2})"},
    {"|", "({1} 或 {2})"},
    {"not", "(不成立 {1})"},
    {"concatenate:with:", "(连接 {1} 和 {2})"},
    {"letter:of:", "({2} 的第 {1} 个字符)"},
    {"stringLength:", "({1} 的字符数)"},
    {"contains:", "({1} 包含 {2}?)"},
    {"%", "({1} 除以 {2} 的余数)"},
    {"\\", "({1} 除以 {2} 的余数)"},
    {"rounded", "(将 {1} 四舍五入)"},
    {"computeFunction:of:", "({2} 的 {1})"},
    {"doAsk", "询问 {1} 并等待"},
    {"answer", "(回答)"},
    {"mousePressed", "按下鼠标?"},
    {"mouseX", "(鼠标 x 坐标)"},
    {"mouseY", "(鼠标 y 坐标)"},
    {"keyPressed:", "按下 {1} 键?"},
    {"timer", "(计时器)"},
    {"timerReset", "计时器归零"},
    {"soundLevel", "(响度)"},
    {"touching:", "碰到 {1}?"},
    {"touchingColor:", "碰到颜色 {1}?"},
    {"color:sees:", "颜色 {1} 碰到 {2}?"},
    {"distanceTo:", "到 {1} 的距离"},
    {"getAttribute:of:", "{2} 的 {1}"},
    {"timeAndDate", "当前 {1}"},
    {"getUserName", "(用户名)"},
    {"readVariable", "{1}"},
    {"setVar:to:", "将 {1} 设为 {2}"},
    {"changeVar:by:", "将 {1} 增加 {2}"},
    {"showVariable:", "显示变量 {1}"},
    {"hideVariable:", "隐藏变量 {1}"},
    {"append:toList:", "将 {1} 加入 {2}"},
    {"deleteLine:ofList:", "删除 {2} 的第 {1} 项"},
    {"insert:at:ofList:", "将 {1} 插入 {2} 的第 {3} 项"},
    {"setLine:ofList:to:", "将 {2} 的第 {1} 项替换为 {3}"},
    {"getLine:ofList:", "{2} 的第 {1} 项"},
    {"lineCountOfList:", "{1} 的项目数"},
    {"list:contains:", "{1} 包含 {2}?"},
    {"contentsOfList:", "{1}"},
    {"hideList:", "隐藏列表 {1}"},
    {"showList:", "显示列表 {1}"},
    {"changeVariable", "将 {1} 增加 {2}"},
    {"setVariable", "将 {1} 设为 {2}"},
    {"doForeverIf", "重复执行 如果 {1}"},
    {"stopAll", "停止全部"},
    {"nextBackground", "下一个背景"},
    {"showBackground:", "换成 {1} 背景"},
    {"scratchComment", "注释 {1}"},
    {"costumeIndex", "(造型编号)"},
    {"backgroundIndex", "(背景编号)"},
    {"sceneName", "(背景名称)"},
    {"scale", "(大小)"},
    {"xpos", "(x 坐标)"},
    {"ypos", "(y 坐标)"},
    {"heading", "(方向)"},
    {"volume", "(音量)"},
    {"tempo", "(节奏)"},
    {"timestamp", "(2000 年以来的天数)"},
    {"isLoud", "很大声?"},
    {"abs", "({1} 的绝对值)"},
    {"sqrt", "({1} 的平方根)"},
    {"drum:duration:elapsed:from:", "演奏鼓 {1} {2} 拍"},
    {"rest:elapsed:from:", "休止 {1} 拍"},
    {"noteOn:duration:elapsed:from:", "演奏音符 {1} {2} 拍"},
    {"midiInstrument:", "将乐器设为 {1}"},
    {"changeTempoBy:", "将节奏增加 {1}"},
    {"setTempoTo:", "将节奏设为 {1} bpm"},
    {"motorOnFor:elapsed:from:", "马达开启 {1} 秒"},
    {"allMotorsOn", "马达开启"},
    {"allMotorsOff", "马达关闭"},
    {"startMotorPower:", "将马达功率设为 {1}"},
    {"sensor:", "({1} 传感器值)"},
    {"sensorPressed:", "({1} 传感器被按下?)"},
};

inline const std::map<std::string, std::string> HAT_EVENTS = {
    {"Scratch-StartClicked", "当 绿旗 被点击"},
    {"Scratch-MouseClickEvent", "当角色被点击"},
    {"Scratch-KeyPressedEvent", "当按下某键"},
    {"Scratch-SensorGreaterThan", "当传感器值超过阈值"},
};

} // namespace sb