// src/sb3_tables.hpp
// Scratch 2/3 积木翻译表（照抄 sb.py），与 sb1_tables.hpp 同样用 inline const。
#pragma once
#include <map>
#include <set>
#include <string>

namespace sb {

inline const std::map<std::string, std::string> SB2_T = {
    {"forward:", "移动 {__1} 步"},
    {"turnRight:", "右转 {__1} 度"},
    {"turnLeft:", "左转 {__1} 度"},
    {"heading:", "面向 {__1} 方向"},
    {"pointTowards:", "面向 {__1} 方向"},
    {"gotoX:y:", "移到 x: {__1} y: {__2}"},
    {"gotoSpriteOrMouse:", "移到 {__1}"},
    {"glideSecs:toX:y:elapsed:from:", "在 {__1} 秒内滑行到 x: {__2} y: {__3}"},
    {"changeXposBy:", "将 x 坐标增加 {__1}"},
    {"xpos:", "将 x 坐标设为 {__1}"},
    {"changeYposBy:", "将 y 坐标增加 {__1}"},
    {"ypos:", "将 y 坐标设为 {__1}"},
    {"bounceOffEdge", "碰到边缘就反弹"},
    {"setRotationStyle", "将旋转方式设为 {__1}"},
    {"xpos", "(x 坐标)"},
    {"ypos", "(y 坐标)"},
    {"heading", "(方向)"},
    {"say:", "说 {__1}"},
    {"say:forSecs:", "说 {__1} {__2} 秒"},
    {"say:duration:elapsed:from:", "说 {__1} {__2} 秒"},
    {"think:", "思考 {__1}"},
    {"think:forSecs:", "思考 {__1} {__2} 秒"},
    {"think:duration:elapsed:from:", "思考 {__1} {__2} 秒"},
    {"show", "显示"},
    {"hide", "隐藏"},
    {"lookLike:", "换成 {__1} 造型"},
    {"nextCostume", "下一个造型"},
    {"startScene", "换成 {__1} 背景"},
    {"nextScene", "下一个背景"},
    {"changeGraphicEffect:by:", "将 {__1} 特效增加 {__2}"},
    {"setGraphicEffect:to:", "将 {__1} 特效设为 {__2}"},
    {"filterReset", "清除图形特效"},
    {"changeSizeBy:", "将大小增加 {__1}"},
    {"setSizeTo:", "将大小设为 {__1}"},
    {"comeToFront", "移到最前面"},
    {"goToFront", "移到最前面"},
    {"goBackByLayers:", "后移 {__1} 层"},
    {"costumeIndex", "(造型编号)"},
    {"costumeName", "(造型名称)"},
    {"backgroundIndex", "(背景编号)"},
    {"sceneName", "(背景名称)"},
    {"scale", "(大小)"},
    {"playSound:", "播放声音 {__1}"},
    {"playSound:wait:", "播放声音 {__1} 等待播完"},
    {"doPlaySoundAndWait", "播放声音 {__1} 等待播完"},
    {"stopAllSounds", "停止所有声音"},
    {"changeVolumeBy:", "将音量增加 {__1}"},
    {"setVolumeTo:", "将音量设为 {__1}"},
    {"volume", "(音量)"},
    {"change Tempo by:", "将节奏增加 {__1}"},
    {"set Tempo to:", "将节奏设为 {__1}"},
    {"tempo", "(节奏)"},
    {"changeTempoBy:", "将节奏增加 {__1}"},
    {"setTempoTo:", "将节奏设为 {__1}"},
    {"drum:duration:elapsed:from:", "演奏鼓 {__1} {__2} 拍"},
    {"rest:elapsed:from:", "休止 {__1} 拍"},
    {"noteOn:duration:elapsed:from:", "演奏音符 {__1} {__2} 拍"},
    {"midiInstrument:", "将乐器设为 {__1}"},
    {"clearPenTrails", "清空画笔"},
    {"stampCostume", "图章"},
    {"putPenDown", "落笔"},
    {"putPenUp", "抬笔"},
    {"penColor:", "将笔的颜色设为 {__1}"},
    {"setPenHueTo:", "将笔的色相设为 {__1}"},
    {"changePenHueBy:", "将笔的色相增加 {__1}"},
    {"setPenShadeTo:", "将笔的明度设为 {__1}"},
    {"changePenShadeBy:", "将笔的明度增加 {__1}"},
    {"setPenSizeTo:", "将笔的粗细设为 {__1}"},
    {"penSize:", "将笔的粗细设为 {__1}"},
    {"changePenSizeBy:", "将笔的粗细增加 {__1}"},
    {"whenGreenFlag", "当 绿旗 被点击"},
    {"whenKeyPressed", "当按下 {__1} 键"},
    {"whenClicked", "当角色被点击"},
    {"whenSceneStarts", "当背景换成 {__1}"},
    {"whenSensorGreaterThan", "当 {__1} > {__2}"},
    {"whenIReceive", "当接收到 {__1}"},
    {"broadcast:", "广播 {__1}"},
    {"doBroadcastAndWait", "广播 {__1} 并等待"},
    {"whenCloned", "当作为克隆体启动时"},
    {"wait:elapsed:from:", "等待 {__1} 秒"},
    {"doRepeat", "重复执行 {__1} 次"},
    {"doForever", "重复执行"},
    {"doIf", "如果 {__1} 那么"},
    {"doIfElse", "如果 {__1} 那么"},
    {"doWaitUntil", "等待直到 {__1}"},
    {"doUntil", "重复执行直到 {__1}"},
    {"stopScripts", "停止 {__1}"},
    {"createCloneOf", "克隆 {__1}"},
    {"deleteClone", "删除此克隆体"},
    {"doAsk", "询问 {__1} 并等待"},
    {"answer", "(回答)"},
    {"keyPressed:", "按下 {__1} 键?"},
    {"mousePressed", "按下鼠标?"},
    {"mouseX", "(鼠标 x 坐标)"},
    {"mouseY", "(鼠标 y 坐标)"},
    {"soundLevel", "(响度)"},
    {"timer", "(计时器)"},
    {"timerReset", "计时器归零"},
    {"distanceTo:", "到 {__1} 的距离"},
    {"touching:", "碰到 {__1}?"},
    {"touchingColor:", "碰到颜色 {__1}?"},
    {"color:sees:", "颜色 {__1} 碰到 {__2}?"},
    {"getAttribute:of:", "{__2} 的 {__1}"},
    {"timeAndDate", "当前{__1}"},
    {"timestamp", "(2000 年以来的天数)"},
    {"getUserName", "(用户名)"},
    {"+", "({__1} + {__2})"},
    {"-", "({__1} - {__2})"},
    {"*", "({__1} × {__2})"},
    {"/", "({__1} ÷ {__2})"},
    {"%", "({__1} 除以 {__2} 的余数)"},
    {"randomFrom:to:", "在 {__1} 到 {__2} 之间取随机数"},
    {">", "({__1} > {__2})"},
    {"<", "({__1} < {__2})"},
    {"=", "({__1} = {__2})"},
    {"&", "({__1} 且 {__2})"},
    {"|", "({__1} 或 {__2})"},
    {"not", "(不成立 {__1})"},
    {"concatenate:with:", "(连接 {__1} 和 {__2})"},
    {"letter:of:", "({__2} 的第 {__1} 个字符)"},
    {"stringLength:", "({__1} 的字符数)"},
    {"contains:", "({__1} 包含 {__2}?)"},
    {"rounded", "(将 {__1} 四舍五入)"},
    {"compute", "({__2} 的 {__1})"},
    {"computeFunction:of:", "({__2} 的 {__1})"},
    {"readVariable", "{__1}"},
    {"setVar:to:", "将 {__1} 设为 {__2}"},
    {"changeVar:by:", "将 {__1} 增加 {__2}"},
    {"showVariable:", "显示变量 {__1}"},
    {"hideVariable:", "隐藏变量 {__1}"},
    {"contentsOfList:", "{__1}"},
    {"append:toList:", "将 {__1} 加入 {__2}"},
    {"deleteLine:ofList:", "删除 {__2} 的第 {__1} 项"},
    {"insert:at:ofList:", "将 {__1} 插入 {__2} 的第 {__3} 项"},
    {"setLine:ofList:to:", "将 {__2} 的第 {__1} 项替换为 {__3}"},
    {"getLine:ofList:", "{__2} 的第 {__1} 项"},
    {"lineCountOfList:", "{__1} 的项目数"},
    {"list:contains:", "{__1} 包含 {__2}?"},
    {"showList:", "显示列表 {__1}"},
    {"hideList:", "隐藏列表 {__1}"},
    {"getParam", "{__1}"},
};

inline const std::map<std::string, std::string> SB2_MENU = {
    {"mouse-pointer", "鼠标指针"}, {"_mouse_", "鼠标指针"}, {"_edge_", "边缘"},
    {"_random_", "随机位置"}, {"myself", "自己"}, {"left-right", "左右翻转"},
    {"don't rotate", "不旋转"}, {"normal", "任意旋转"},
    {"color", "颜色"}, {"fisheye", "鱼眼"}, {"whirl", "漩涡"}, {"pixelate", "像素化"},
    {"mosaic", "马赛克"}, {"brightness", "亮度"}, {"ghost", "虚像"},
    {"all", "全部脚本"}, {"this script", "这个脚本"},
    {"other scripts in sprite", "该角色的其他脚本"},
    {"year", "年"}, {"month", "月"}, {"date", "日"}, {"day", "星期"},
    {"hour", "时"}, {"minute", "分"}, {"second", "秒"},
    {"x position", "x 坐标"}, {"y position", "y 坐标"}, {"direction", "方向"},
    {"costume #", "造型编号"}, {"costume name", "造型名称"}, {"size", "大小"},
    {"volume", "音量"}, {"loudness", "响度"}, {"timer", "计时器"},
    {"space", "空格"}, {"up arrow", "↑"}, {"down arrow", "↓"},
    {"right arrow", "→"}, {"left arrow", "←"}, {"any", "任意"}, {"enter", "回车"},
    {"abs", "绝对值"}, {"floor", "向下取整"}, {"ceiling", "向上取整"}, {"sqrt", "平方根"},
    {"sin", "正弦"}, {"cos", "余弦"}, {"tan", "正切"}, {"asin", "反正弦"},
    {"acos", "反余弦"}, {"atan", "反正切"}, {"ln", "ln"}, {"log", "log"},
    {"e ^", "e 的次方"}, {"10 ^", "10 的次方"},
};

inline const std::map<std::string, std::string> SB3_T = {
    {"motion_movesteps", "移动 {STEPS} 步"},
    {"motion_turnright", "右转 {DEGREES} 度"},
    {"motion_turnleft", "左转 {DEGREES} 度"},
    {"motion_goto", "移到 {TO}"},
    {"motion_gotoxy", "移到 x: {X} y: {Y}"},
    {"motion_glideto", "在 {SECS} 秒内滑行到 {TO}"},
    {"motion_glidesecstoxy", "在 {SECS} 秒内滑行到 x: {X} y: {Y}"},
    {"motion_pointindirection", "面向 {DIRECTION} 方向"},
    {"motion_pointtowards", "面向 {TOWARDS} 方向"},
    {"motion_changexby", "将 x 坐标增加 {DX}"},
    {"motion_setx", "将 x 坐标设为 {X}"},
    {"motion_changeyby", "将 y 坐标增加 {DY}"},
    {"motion_sety", "将 y 坐标设为 {Y}"},
    {"motion_ifonedgebounce", "碰到边缘就反弹"},
    {"motion_setrotationstyle", "将旋转方式设为 {STYLE}"},
    {"motion_xposition", "(x 坐标)"},
    {"motion_yposition", "(y 坐标)"},
    {"motion_direction", "(方向)"},
    {"looks_sayforsecs", "说 {MESSAGE} {SECS} 秒"},
    {"looks_say", "说 {MESSAGE}"},
    {"looks_thinkforsecs", "思考 {MESSAGE} {SECS} 秒"},
    {"looks_think", "思考 {MESSAGE}"},
    {"looks_switchcostumeto", "换成 {COSTUME} 造型"},
    {"looks_nextcostume", "下一个造型"},
    {"looks_switchbackdropto", "换成 {BACKDROP} 背景"},
    {"looks_nextbackdrop", "下一个背景"},
    {"looks_changesizeby", "将大小增加 {CHANGE}"},
    {"looks_setsizeto", "将大小设为 {SIZE}"},
    {"looks_changeeffectby", "将 {EFFECT} 特效增加 {CHANGE}"},
    {"looks_seteffectto", "将 {EFFECT} 特效设为 {VALUE}"},
    {"looks_cleargraphiceffects", "清除图形特效"},
    {"looks_show", "显示"},
    {"looks_hide", "隐藏"},
    {"looks_gotofrontback", "移到{FRONT_BACK}"},
    {"looks_goforwardbackwardlayers", "{FORWARD_BACKWARD} {NUM} 层"},
    {"looks_costumenumbername", "造型{NUMBER_NAME}"},
    {"looks_backdropnumbername", "背景{NUMBER_NAME}"},
    {"looks_size", "(大小)"},
    {"sound_play", "播放声音 {SOUND_MENU}"},
    {"sound_playuntildone", "播放声音 {SOUND_MENU} 等待播完"},
    {"sound_stopallsounds", "停止所有声音"},
    {"sound_changeeffectby", "将 {EFFECT} 音效增加 {VALUE}"},
    {"sound_seteffectto", "将 {EFFECT} 音效设为 {VALUE}"},
    {"sound_cleareffects", "清除音效"},
    {"sound_changevolumeby", "将音量增加 {VOLUME}"},
    {"sound_setvolumeto", "将音量设为 {VOLUME}"},
    {"sound_volume", "(音量)"},
    {"event_whenflagclicked", "当 绿旗 被点击"},
    {"event_whenkeypressed", "当按下 {KEY_OPTION} 键"},
    {"event_whenthisspriteclicked", "当角色被点击"},
    {"event_whenstageclicked", "当舞台被点击"},
    {"event_whenbackdropswitchesto", "当背景换成 {BACKDROP}"},
    {"event_whengreaterthan", "当 {WHENGREATERTHANMENU} > {VALUE}"},
    {"event_whenbroadcastreceived", "当接收到 {BROADCAST_OPTION}"},
    {"event_whencloned", "当作为克隆体启动时"},
    {"event_broadcast", "广播 {BROADCAST_INPUT}"},
    {"event_broadcastandwait", "广播 {BROADCAST_INPUT} 并等待"},
    {"control_wait", "等待 {DURATION} 秒"},
    {"control_repeat", "重复执行 {TIMES} 次"},
    {"control_forever", "重复执行"},
    {"control_if", "如果 {CONDITION} 那么"},
    {"control_if_else", "如果 {CONDITION} 那么"},
    {"control_wait_until", "等待直到 {CONDITION}"},
    {"control_repeat_until", "重复执行直到 {CONDITION}"},
    {"control_while", "当 {CONDITION} 重复执行"},
    {"control_for_each", "对于 {VARIABLE} 中的每个 {VALUE}"},
    {"control_stop", "停止 {STOP_OPTION}"},
    {"control_start_as_clone", "当作为克隆体启动时"},
    {"control_create_clone_of", "克隆 {CLONE_OPTION}"},
    {"control_delete_this_clone", "删除此克隆体"},
    {"sensing_touchingobject", "碰到 {TOUCHINGOBJECTMENU}?"},
    {"sensing_touchingcolor", "碰到颜色 {COLOR}?"},
    {"sensing_coloristouchingcolor", "颜色 {COLOR} 碰到 {COLOR2}?"},
    {"sensing_distanceto", "到 {DISTANCETOMENU} 的距离"},
    {"sensing_askandwait", "询问 {QUESTION} 并等待"},
    {"sensing_answer", "(回答)"},
    {"sensing_keypressed", "按下 {KEY_OPTION} 键?"},
    {"sensing_mousedown", "按下鼠标?"},
    {"sensing_mousex", "(鼠标 x 坐标)"},
    {"sensing_mousey", "(鼠标 y 坐标)"},
    {"sensing_loudness", "(响度)"},
    {"sensing_timer", "(计时器)"},
    {"sensing_resettimer", "计时器归零"},
    {"sensing_of", "{OBJECT} 的 {PROPERTY}"},
    {"sensing_current", "当前{CURRENTMENU}"},
    {"sensing_dayssince2000", "(2000 年以来的天数)"},
    {"sensing_username", "(用户名)"},
    {"sensing_setdragmode", "将拖动模式设为 {DRAG_MODE}"},
    {"operator_add", "({NUM1} + {NUM2})"},
    {"operator_subtract", "({NUM1} - {NUM2})"},
    {"operator_multiply", "({NUM1} × {NUM2})"},
    {"operator_divide", "({NUM1} ÷ {NUM2})"},
    {"operator_random", "在 {FROM} 到 {TO} 之间取随机数"},
    {"operator_gt", "({OPERAND1} > {OPERAND2})"},
    {"operator_lt", "({OPERAND1} < {OPERAND2})"},
    {"operator_equals", "({OPERAND1} = {OPERAND2})"},
    {"operator_and", "({OPERAND1} 且 {OPERAND2})"},
    {"operator_or", "({OPERAND1} 或 {OPERAND2})"},
    {"operator_not", "(不成立 {OPERAND})"},
    {"operator_join", "(连接 {STRING1} 和 {STRING2})"},
    {"operator_letter_of", "({STRING} 的第 {LETTER} 个字符)"},
    {"operator_length", "({STRING} 的字符数)"},
    {"operator_contains", "({STRING1} 包含 {STRING2}?)"},
    {"operator_mod", "({NUM1} 除以 {NUM2} 的余数)"},
    {"operator_round", "(将 {NUM} 四舍五入)"},
    {"operator_mathop", "({NUM} 的 {OPERATOR})"},
    {"data_variable", "{VARIABLE}"},
    {"data_setvariableto", "将 {VARIABLE} 设为 {VALUE}"},
    {"data_changevariableby", "将 {VARIABLE} 增加 {VALUE}"},
    {"data_showvariable", "显示变量 {VARIABLE}"},
    {"data_hidevariable", "隐藏变量 {VARIABLE}"},
    {"data_listcontents", "{LIST}"},
    {"data_addtolist", "将 {ITEM} 加入 {LIST}"},
    {"data_deleteoflist", "删除 {LIST} 的第 {INDEX} 项"},
    {"data_deletealloflist", "删除 {LIST} 的全部项目"},
    {"data_insertatlist", "将 {ITEM} 插入 {LIST} 的第 {INDEX} 项"},
    {"data_replaceitemoflist", "将 {LIST} 的第 {INDEX} 项替换为 {ITEM}"},
    {"data_itemoflist", "{LIST} 的第 {INDEX} 项"},
    {"data_itemnumoflist", "{ITEM} 在 {LIST} 中的编号"},
    {"data_lengthoflist", "{LIST} 的项目数"},
    {"data_listcontainsitem", "{LIST} 包含 {ITEM}?"},
    {"data_showlist", "显示列表 {LIST}"},
    {"data_hidelist", "隐藏列表 {LIST}"},
    {"argument_reporter_string_number", "{VALUE}"},
    {"argument_reporter_boolean", "{VALUE}"},
    {"sound_sounds_menu", "{SOUND_MENU}"},
    {"looks_costume", "{COSTUME}"},
    {"looks_backdrops", "{BACKDROP}"},
    {"motion_goto_menu", "{TO}"},
    {"motion_glideto_menu", "{TO}"},
    {"motion_pointtowards_menu", "{TOWARDS}"},
    {"sensing_touchingobjectmenu", "{TOUCHINGOBJECTMENU}"},
    {"sensing_distancetomenu", "{DISTANCETOMENU}"},
    {"sensing_keyoptions", "{KEY_OPTION}"},
    {"sensing_of_object_menu", "{OBJECT}"},
    {"control_create_clone_of_menu", "{CLONE_OPTION}"},
    {"event_broadcast_menu", "{BROADCAST_OPTION}"},
    {"pen_clear", "清空画笔"},
    {"pen_stamp", "图章"},
    {"pen_penDown", "落笔"},
    {"pen_penUp", "抬笔"},
    {"pen_setPenColorToColor", "将笔的颜色设为 {COLOR}"},
    {"pen_changePenColorParamBy", "将笔的 {COLOR_PARAM} 增加 {VALUE}"},
    {"pen_setPenColorParamTo", "将笔的 {COLOR_PARAM} 设为 {VALUE}"},
    {"pen_menu_colorParam", "{COLOR_PARAM}"},
    {"pen_changePenSizeBy", "将笔的粗细增加 {SIZE}"},
    {"pen_setPenSizeTo", "将笔的粗细设为 {SIZE}"},
    {"pen_setPenShadeToNumber", "将笔的色相设为 {SHADE}"},
    {"pen_changePenShadeBy", "将笔的色相增加 {SHADE}"},
};

inline const std::map<std::string, std::map<std::string, std::string>> FIELD_MAP = {
    {"EFFECT", {{"COLOR","颜色"},{"FISHEYE","鱼眼"},{"WHIRL","漩涡"},
                {"PIXELATE","像素化"},{"MOSAIC","马赛克"},{"BRIGHTNESS","亮度"},
                {"GHOST","虚像"}}},
    {"STYLE",  {{"left-right","左右翻转"},{"don't rotate","不旋转"},
                {"all around","任意旋转"}}},
    {"FRONT_BACK", {{"front","最前面"},{"back","最后面"}}},
    {"FORWARD_BACKWARD", {{"forward","前移"},{"backward","后移"}}},
    {"NUMBER_NAME", {{"number","编号"},{"name","名称"}}},
    {"COLOR_PARAM", {{"color","颜色"},{"brightness","亮度"},{"saturation","饱和度"}}},
    {"STOP_OPTION", {{"all","全部脚本"},{"this script","这个脚本"},
                     {"other scripts in sprite","该角色的其他脚本"},
                     {"other scripts in stage","舞台的其他脚本"}}},
    {"CURRENTMENU", {{"YEAR","年"},{"MONTH","月"},{"DATE","日"},{"DAY","星期"},
                     {"HOUR","时"},{"MINUTE","分"},{"SECOND","秒"}}},
    {"PROPERTY", {{"x position","x 坐标"},{"y position","y 坐标"},{"direction","方向"},
                  {"costume #","造型编号"},{"costume name","造型名称"},{"size","大小"},
                  {"volume","音量"},{"position","位置"},{"backdrop #","背景编号"},
                  {"backdrop name","背景名称"}}},
    {"OPERATOR", {{"abs","绝对值"},{"floor","向下取整"},{"ceiling","向上取整"},{"sqrt","平方根"},
                  {"sin","正弦"},{"cos","余弦"},{"tan","正切"},{"asin","反正弦"},
                  {"acos","反余弦"},{"atan","反正切"},{"ln","ln"},{"log","log"},
                  {"e ^","e 的次方"},{"10 ^","10 的次方"}}},
    {"SOUND_EFFECT", {{"PITCH","音高"},{"PAN","左右平衡"}}},
    {"KEY_OPTION", {{"space","空格"},{"up arrow","↑"},{"down arrow","↓"},
                    {"right arrow","→"},{"left arrow","←"},{"any","任意"},{"enter","回车"}}},
    {"WHENGREATERTHANMENU", {{"LOUDNESS","响度"},{"TIMER","计时器"}}},
    {"BROADCAST_OPTION", {}},
};

// 哪些 SB2 opcode 的第几个输入是菜单（SB2_MENU_POS）
inline const std::map<std::string, std::set<int>> SB2_MENU_POS_MAP = {
    {"pointTowards:", {1}}, {"gotoSpriteOrMouse:", {1}}, {"setRotationStyle", {1}},
    {"changeGraphicEffect:by:", {1}}, {"setGraphicEffect:to:", {1}},
    {"whenKeyPressed", {1}}, {"keyPressed:", {1}}, {"touching:", {1}},
    {"distanceTo:", {1}}, {"getAttribute:of:", {1}}, {"timeAndDate", {1}},
    {"stopScripts", {1}}, {"createCloneOf", {1}}, {"whenSensorGreaterThan", {1}},
    {"compute", {1}}, {"computeFunction:of:", {1}},
};

// ---------------------------------------------------------------------------
// 内置扩展积木（从 turbowarp-vm 源码提取）
// 类型: 0=COMMAND 1=REPORTER 2=BOOLEAN 3=HAT
// opcode 形如 <扩展id>_<块opcode>（Scratch 3 扩展约定，与 SB3_T 的 pen_* 同构）
// ---------------------------------------------------------------------------
inline const std::map<std::string, int> EXT_BLOCK_TYPES = {
    {"boost_motorOnFor", 0},
    {"boost_motorOnForRotation", 0},
    {"boost_motorOn", 0},
    {"boost_motorOff", 0},
    {"boost_setMotorPower", 0},
    {"boost_setMotorDirection", 0},
    {"boost_getMotorPosition", 1},
    {"boost_whenColor", 3},
    {"boost_seeingColor", 2},
    {"boost_whenTilted", 3},
    {"boost_getTiltAngle", 1},
    {"boost_setLightHue", 0},
    {"ev3_motorTurnClockwise", 0},
    {"ev3_motorTurnCounterClockwise", 0},
    {"ev3_motorSetPower", 0},
    {"ev3_getMotorPosition", 1},
    {"ev3_whenButtonPressed", 3},
    {"ev3_whenDistanceLessThan", 3},
    {"ev3_whenBrightnessLessThan", 3},
    {"ev3_buttonPressed", 2},
    {"ev3_getDistance", 1},
    {"ev3_getBrightness", 1},
    {"ev3_beep", 0},
    {"gdxfor_whenGesture", 3},
    {"gdxfor_whenForcePushedOrPulled", 3},
    {"gdxfor_getForce", 1},
    {"gdxfor_whenTilted", 3},
    {"gdxfor_isTilted", 2},
    {"gdxfor_getTilt", 1},
    {"gdxfor_isFreeFalling", 2},
    {"gdxfor_getSpinSpeed", 1},
    {"gdxfor_getAcceleration", 1},
    {"makeymakey_whenMakeyKeyPressed", 3},
    {"makeymakey_whenCodePressed", 3},
    {"microbit_whenButtonPressed", 3},
    {"microbit_isButtonPressed", 2},
    {"microbit_whenGesture", 3},
    {"microbit_displaySymbol", 0},
    {"microbit_displayText", 0},
    {"microbit_displayClear", 0},
    {"microbit_whenTilted", 3},
    {"microbit_isTilted", 2},
    {"microbit_getTiltAngle", 1},
    {"microbit_whenPinConnected", 3},
    {"music_playDrumForBeats", 0},
    {"music_midiPlayDrumForBeats", 0},
    {"music_restForBeats", 0},
    {"music_playNoteForBeats", 0},
    {"music_setInstrument", 0},
    {"music_midiSetInstrument", 0},
    {"music_setTempo", 0},
    {"music_changeTempo", 0},
    {"music_getTempo", 1},
    {"pen_clear", 0},
    {"pen_stamp", 0},
    {"pen_penDown", 0},
    {"pen_penUp", 0},
    {"pen_setPenColorToColor", 0},
    {"pen_changePenColorParamBy", 0},
    {"pen_setPenColorParamTo", 0},
    {"pen_changePenSizeBy", 0},
    {"pen_setPenSizeTo", 0},
    {"pen_setPenShadeToNumber", 0},
    {"pen_changePenShadeBy", 0},
    {"pen_setPenHueToNumber", 0},
    {"pen_changePenHueBy", 0},
    {"speech2text_listenAndWait", 0},
    {"speech2text_whenIHearHat", 3},
    {"speech2text_getSpeech", 1},
    {"text2speech_speakAndWait", 0},
    {"text2speech_setVoice", 0},
    {"text2speech_setLanguage", 0},
    {"translate_getTranslate", 1},
    {"translate_getViewerLanguage", 1},
    {"tw_getLastKeyPressed", 1},
    {"tw_getButtonIsDown", 2},
    {"videoSensing_whenMotionGreaterThan", 3},
    {"videoSensing_videoOn", 1},
    {"videoSensing_videoToggle", 0},
    {"videoSensing_setVideoTransparency", 0},
    {"wedo2_motorOnFor", 0},
    {"wedo2_motorOn", 0},
    {"wedo2_motorOff", 0},
    {"wedo2_startMotorPower", 0},
    {"wedo2_setMotorDirection", 0},
    {"wedo2_setLightHue", 0},
    {"wedo2_playNoteFor", 0},
    {"wedo2_whenDistance", 3},
    {"wedo2_whenTilted", 3},
    {"wedo2_getDistance", 1},
    {"wedo2_isTilted", 2},
    {"wedo2_getTiltAngle", 1},
};

// 扩展 id → 中文/显示名
inline const std::map<std::string, std::string> EXT_NAMES = {
    {"boost", "LEGO BOOST"},
    {"ev3", "LEGO MINDSTORMS EV3"},
    {"gdxfor", "Go Direct Force & Acceleration"},
    {"makeymakey", "Makey Makey"},
    {"microbit", "micro:bit"},
    {"music", "音乐"},
    {"pen", "画笔"},
    {"speech2text", "语音识别"},
    {"text2speech", "文字转语音"},
    {"translate", "翻译"},
    {"tw", "TurboWarp"},
    {"videoSensing", "视频侦测"},
    {"wedo2", "LEGO Education WeDo 2.0"},
};

// ---------------------------------------------------------------------------
// 自定义扩展积木（从扩展 JS 的 getInfo() 解析，见 tools/extract_ext.js）
// 与内置扩展同构：opcode = <扩展id>_<块opcode>，类型同上（0..3）
// ---------------------------------------------------------------------------
inline const std::map<std::string, int> CUSTOM_EXT_BLOCK_TYPES = {
    {"acrylicextension_applyAcrylicToStage", 0},
    {"acrylicextension_createAcrylicPanel", 0},
    {"acrylicextension_createStyledPanel", 0},
    {"acrylicextension_createAcrylicPanelSmooth", 0},
    {"acrylicextension_createStyledPanelSmooth", 0},
    {"acrylicextension_removePanel", 0},
    {"acrylicextension_removePanelSmooth", 0},
    {"acrylicextension_removeAllPanels", 0},
    {"acrylicextension_removeAllPanelsSmooth", 0},
    {"acrylicextension_smoothMoveTo", 0},
    {"acrylicextension_smoothMovePanelX", 0},
    {"acrylicextension_smoothMovePanelY", 0},
    {"acrylicextension_setPanelPosition", 0},
    {"acrylicextension_getPanelX", 1},
    {"acrylicextension_getPanelY", 1},
    {"acrylicextension_setFrameRate", 0},
    {"acrylicextension_clearAllAcrylic", 0},
    {"costumebase64_getCurrentCostumeBase64", 1},
    {"costumebase64_getCostumeBase64", 1},
    {"costumebase64_getCurrentCostumeSize", 1},
    {"costumebase64_saveCostumeToFile", 0},
    {"yc6ncolormaster_blendColors", 1},
    {"yc6ncolormaster_blendMultipleColors", 1},
    {"yc6ncolormaster_adjustBrightness", 1},
    {"yc6ncolormaster_adjustSaturationFixed", 1},
    {"yc6ncolormaster_getHSLValues", 1},
    {"yc6ncolormaster_hslToColor", 1},
    {"yc6ncolormaster_setTransparency", 1},
    {"yc6ncolormaster_testSaturationAdjustment", 1},
    {"yc6ncolormaster_verifyColor", 1},
    {"yc6ncolormaster_rgbToHex", 1},
    {"yc6ncolormaster_hexToRgbString", 1},
    {"yc6ncolormaster_nameToColor", 1},
    {"yc6ncolormaster_randomColor", 1},
    // 社区扩展（extensions.turbowarp.org/encoding.js，作者 -SIPC-）
    {"Encoding_encode", 1},
    {"Encoding_decode", 1},
    {"Encoding_hash", 1},
    {"Encoding_Conversioncodes", 1},
    {"Encoding_Restorecode", 1},
    {"Encoding_Randomstrings", 1},
    {"Encoding_Fontgenerationstring", 1},
    // 菜单桩
    {"Encoding_menu_encode", 1},
    {"Encoding_menu_hash", 1},
    {"Encoding_menu_CodeList", 1},
    {"yc6nimageprocessor_loadImage", 1},
    {"yc6nimageprocessor_getImageSize", 1},
    {"yc6npathfinder_initMap", 0},
    {"yc6npathfinder_initMapWithMatrix", 0},
    {"yc6npathfinder_setObstacle", 0},
    {"yc6npathfinder_clearMap", 0},
    {"yc6npathfinder_findPathBFS", 1},
    {"yc6npathfinder_findPathDFS", 1},
    {"yc6npathfinder_findPathAStar", 1},
    {"yc6npathfinder_findPathWeightedAStar", 1},
    {"yc6npathfinder_findPathDijkstra", 1},
    {"yc6npathfinder_visualizePath", 0},
    {"yc6npathfinder_getMapString", 1},
    {"yc6npathfinder_getPathString", 1},
    {"yc6npathfinder_getLastPath", 1},
    {"yc6npathfinder_clearPath", 0},
};

// 自定义扩展 id → 名称
inline const std::map<std::string, std::string> CUSTOM_EXT_NAMES = {
    {"acrylicextension", "亚克力效果"},
    {"costumebase64", "造型Base64工具"},
    {"yc6ncolormaster", "调色大师（精确版）"},
    {"yc6nimageprocessor", "简易图像处理扩展"},
    {"yc6npathfinder", "完整寻路引擎"},
    {"Encoding", "编码（Encoding）"},
};

// === 自动解析的扩展积木表（tools/build_ext_tables.js 生成）===
inline const std::map<std::string, int> AUTO_EXT_BLOCK_TYPES = {
    {"Encoding_Conversioncodes", 1},
    {"Encoding_Fontgenerationstring", 1},
    {"Encoding_Randomstrings", 1},
    {"Encoding_Restorecode", 1},
    {"Encoding_decode", 1},
    {"Encoding_encode", 1},
    {"Encoding_hash", 1},
    {"Encoding_menu_Code", 1},
    {"Encoding_menu_encode", 1},
    {"Encoding_menu_hash", 1},
    {"MouseCursor_getCur", 1},
    {"MouseCursor_hideCur", 0},
    {"MouseCursor_menu_cursors", 1},
    {"MouseCursor_menu_imagePositions", 1},
    {"MouseCursor_menu_imageSizes", 1},
    {"MouseCursor_setCur", 0},
    {"MouseCursor_setCursorImage", 0},
    {"SPcamera_bindTarget", 0},
    {"SPcamera_changeX", 0},
    {"SPcamera_changeY", 0},
    {"SPcamera_changeZoom", 0},
    {"SPcamera_fixedMouseX", 1},
    {"SPcamera_fixedMouseY", 1},
    {"SPcamera_getDirection", 1},
    {"SPcamera_getDirectionNew", 1},
    {"SPcamera_getX", 1},
    {"SPcamera_getY", 1},
    {"SPcamera_getZoom", 1},
    {"SPcamera_goToObject", 0},
    {"SPcamera_isPreciseMode", 2},
    {"SPcamera_menu_CAMERAS", 1},
    {"SPcamera_menu_EXACT_OBJECTS", 1},
    {"SPcamera_menu_OBJECTS", 1},
    {"SPcamera_menu_TARGETS", 1},
    {"SPcamera_menu_TOGGLER", 1},
    {"SPcamera_moveSteps", 0},
    {"SPcamera_pointCamera", 0},
    {"SPcamera_renderedX", 1},
    {"SPcamera_renderedY", 1},
    {"SPcamera_setDirection", 0},
    {"SPcamera_setDirectionNew", 0},
    {"SPcamera_setSpaceColor", 0},
    {"SPcamera_setX", 0},
    {"SPcamera_setXY", 0},
    {"SPcamera_setY", 0},
    {"SPcamera_setZoom", 0},
    {"SPcamera_spaceColor", 1},
    {"SPcamera_targetCamera", 1},
    {"SPcamera_togglePrecision", 0},
    {"SPcamera_turnCamLeft", 0},
    {"SPcamera_turnCamRight", 0},
    {"SPcamera_unbindTarget", 0},
    {"SPcamera_undefined", 0},
    {"SPcamera_undefined", 0},
    {"SPcamera_undefined", 0},
    {"SPcamera_undefined", 0},
    {"WhenKeyPress_getCurrentKeys", 1},
    {"WhenKeyPress_getLastKey", 1},
    {"WhenKeyPress_keys", 3},
    {"battery_chargeTime", 1},
    {"battery_chargeTimeChanged", 0},
    {"battery_charging", 2},
    {"battery_chargingChanged", 0},
    {"battery_dischargeTime", 1},
    {"battery_dischargeTimeChanged", 0},
    {"battery_level", 1},
    {"battery_levelChanged", 0},
    {"clipboard_clipboard", 1},
    {"clipboard_getLastPastedText", 1},
    {"clipboard_resetClipboard", 0},
    {"clipboard_setClipboard", 0},
    {"clipboard_whenCopied", 0},
    {"clipboard_whenPasted", 0},
    {"cubesterKeySimulation_clickMouse", 0},
    {"cubesterKeySimulation_menu_AND_WAIT", 1},
    {"cubesterKeySimulation_menu_BUTTONS", 1},
    {"cubesterKeySimulation_menu_KEYS", 1},
    {"cubesterKeySimulation_moveMouse", 0},
    {"cubesterKeySimulation_pressKey", 0},
    {"cubesterWindowControls_changeH", 0},
    {"cubesterWindowControls_changeTitleTo", 0},
    {"cubesterWindowControls_changeW", 0},
    {"cubesterWindowControls_changeX", 0},
    {"cubesterWindowControls_changeY", 0},
    {"cubesterWindowControls_closeWindow", 0},
    {"cubesterWindowControls_enterFullscreen", 0},
    {"cubesterWindowControls_exitFullscreen", 0},
    {"cubesterWindowControls_isFocused", 2},
    {"cubesterWindowControls_isFullscreen", 2},
    {"cubesterWindowControls_isTouchingEdge", 2},
    {"cubesterWindowControls_matchStageSize", 0},
    {"cubesterWindowControls_menu_MOVE", 1},
    {"cubesterWindowControls_menu_RESIZE", 1},
    {"cubesterWindowControls_moveTo", 0},
    {"cubesterWindowControls_moveToPresets", 0},
    {"cubesterWindowControls_resizeTo", 0},
    {"cubesterWindowControls_resizeToPresets", 0},
    {"cubesterWindowControls_screenH", 1},
    {"cubesterWindowControls_screenW", 1},
    {"cubesterWindowControls_setH", 0},
    {"cubesterWindowControls_setW", 0},
    {"cubesterWindowControls_setX", 0},
    {"cubesterWindowControls_setY", 0},
    {"cubesterWindowControls_undefined", 0},
    {"cubesterWindowControls_undefined", 0},
    {"cubesterWindowControls_windowH", 1},
    {"cubesterWindowControls_windowTitle", 1},
    {"cubesterWindowControls_windowW", 1},
    {"cubesterWindowControls_windowX", 1},
    {"cubesterWindowControls_windowY", 1},
    {"cyberexplorertoolboxmini_getCurrentKeys", 1},
    {"cyberexplorertoolboxmini_getLastKey", 1},
    {"cyberexplorertoolboxmini_keys", 3},
    {"deepseekapi_addContext", 0},
    {"deepseekapi_askQuestion", 0},
    {"deepseekapi_getContextCount", 1},
    {"deepseekapi_getResponse", 1},
    {"deepseekapi_getStreamResponse", 1},
    {"deepseekapi_getTokenCount", 1},
    {"deepseekapi_menu_contextRoles", 1},
    {"deepseekapi_menu_streamOptions", 1},
    {"deepseekapi_resetContext", 0},
    {"deepseekapi_setStreaming", 0},
    {"files_download", 0},
    {"files_downloadURL", 0},
    {"files_menu_automaticallyOpen", 1},
    {"files_menu_encoding", 1},
    {"files_setOpenMode", 0},
    {"files_showPicker", 1},
    {"files_showPickerAs", 1},
    {"files_showPickerExtensions", 1},
    {"files_showPickerExtensionsAs", 1},
    {"fullscreen0419_fullscreen", 0},
    {"fullscreen0419_isInFullscreen", 2},
    {"fullscreen0419_menu_fullscreenMenu", 1},
    {"fullscreen0419_menu_whenfullscreenMenu", 1},
    {"fullscreen0419_whenfullscreen", 0},
    {"gaussianBlur_applyBlur", 1},
    {"gaussianBlur_resizeImage", 1},
    {"iframe_close", 0},
    {"iframe_display", 0},
    {"iframe_displayHTML", 0},
    {"iframe_get", 1},
    {"iframe_hide", 0},
    {"iframe_iframeMessage", 1},
    {"iframe_menu_getMenu", 1},
    {"iframe_menu_interactiveMenu", 1},
    {"iframe_menu_resizeMenu", 1},
    {"iframe_parentMessage", 1},
    {"iframe_sendMessage", 0},
    {"iframe_sendMessageParent", 0},
    {"iframe_setHeight", 0},
    {"iframe_setInteractive", 0},
    {"iframe_setResize", 0},
    {"iframe_setWidth", 0},
    {"iframe_setX", 0},
    {"iframe_setY", 0},
    {"iframe_show", 0},
    {"iframe_whenMessage", 0},
    {"iframe_whenMessageParent", 0},
    {"jeremygamerTweening_menu_direction", 1},
    {"jeremygamerTweening_menu_modes", 1},
    {"jeremygamerTweening_menu_properties", 1},
    {"jeremygamerTweening_menu_vars", 1},
    {"jeremygamerTweening_tweenProperty", 0},
    {"jeremygamerTweening_tweenValue", 1},
    {"jeremygamerTweening_tweenVariable", 0},
    {"jeremygamerTweening_tweenXY", 0},
    {"lmsAssets_addCostume", 0},
    {"lmsAssets_addSound", 0},
    {"lmsAssets_addSprite", 0},
    {"lmsAssets_deleteCostume", 0},
    {"lmsAssets_deleteSound", 0},
    {"lmsAssets_deleteSprite", 0},
    {"lmsAssets_getAllCostumes", 1},
    {"lmsAssets_getAllSounds", 1},
    {"lmsAssets_getAllSprites", 1},
    {"lmsAssets_getCostumeAtIndex", 1},
    {"lmsAssets_getCostumeData", 1},
    {"lmsAssets_getLoadedExtensions", 1},
    {"lmsAssets_getProjectJSON", 1},
    {"lmsAssets_getProjectValue", 1},
    {"lmsAssets_getSoundAtIndex", 1},
    {"lmsAssets_getSoundData", 1},
    {"lmsAssets_getSpriteName", 1},
    {"lmsAssets_getSpriteValue", 1},
    {"lmsAssets_getSpriteValue2", 1},
    {"lmsAssets_loadExtension", 0},
    {"lmsAssets_menu_attribute", 1},
    {"lmsAssets_menu_project", 1},
    {"lmsAssets_menu_sprite", 1},
    {"lmsAssets_menu_targets", 1},
    {"lmsAssets_openProject", 0},
    {"lmsAssets_renameCostume", 0},
    {"lmsAssets_renameSound", 0},
    {"lmsAssets_renameSprite", 0},
    {"lmsAssets_reorderCostume", 0},
    {"lmsAssets_reorderSound", 0},
    {"lmsLooksPlus_colorHex", 1},
    {"lmsLooksPlus_costumeAttribute", 1},
    {"lmsLooksPlus_costumeContent", 1},
    {"lmsLooksPlus_effectValue", 1},
    {"lmsLooksPlus_hideSprite", 0},
    {"lmsLooksPlus_menu_SVGPNG", 1},
    {"lmsLooksPlus_menu_contentType", 1},
    {"lmsLooksPlus_menu_costumeAttribute", 1},
    {"lmsLooksPlus_menu_effectMenu", 1},
    {"lmsLooksPlus_menu_spriteMenu", 1},
    {"lmsLooksPlus_replaceColors", 1},
    {"lmsLooksPlus_replaceCostumeContent", 0},
    {"lmsLooksPlus_replaceCostumeContentNew", 0},
    {"lmsLooksPlus_restoreCostumeContent", 0},
    {"lmsLooksPlus_setLayerTo", 0},
    {"lmsLooksPlus_showSprite", 0},
    {"lmsLooksPlus_snapshotStage", 1},
    {"lmsLooksPlus_spriteLayerNumber", 1},
    {"lmsLooksPlus_spriteVisible", 2},
    {"lmsLooksPlus_targetCostumeNumber", 1},
    {"lmsSkins_deleteAllSkins", 0},
    {"lmsSkins_deleteSkin", 0},
    {"lmsSkins_getCurrentSkin", 1},
    {"lmsSkins_getSkinAttribute", 1},
    {"lmsSkins_getSkinLoaded", 2},
    {"lmsSkins_menu_skinAttributes", 1},
    {"lmsSkins_menu_targetMenu", 1},
    {"lmsSkins_registerCostumeSkin", 0},
    {"lmsSkins_registerSVGSkin", 0},
    {"lmsSkins_registerURLSkin", 0},
    {"lmsSkins_restoreSkin", 0},
    {"lmsSkins_restoreTargets", 0},
    {"lmsSkins_setSkin", 0},
    {"lmsSoundExpanded_attributeOfSound", 1},
    {"lmsSoundExpanded_changeProjectVolume", 0},
    {"lmsSoundExpanded_getProjectVolume", 1},
    {"lmsSoundExpanded_getSoundEffect", 1},
    {"lmsSoundExpanded_isLooping", 2},
    {"lmsSoundExpanded_isSoundPlaying", 2},
    {"lmsSoundExpanded_menu_attribute", 1},
    {"lmsSoundExpanded_menu_effect", 1},
    {"lmsSoundExpanded_menu_preciseTargets", 1},
    {"lmsSoundExpanded_menu_targets", 1},
    {"lmsSoundExpanded_pauseSounds", 0},
    {"lmsSoundExpanded_playSoundAt", 0},
    {"lmsSoundExpanded_playSoundAtAndWait", 0},
    {"lmsSoundExpanded_playSoundTo", 0},
    {"lmsSoundExpanded_playSoundToAndWait", 0},
    {"lmsSoundExpanded_resumeSounds", 0},
    {"lmsSoundExpanded_setProjectVolume", 0},
    {"lmsSoundExpanded_startLooping", 0},
    {"lmsSoundExpanded_startLoopingBegin", 0},
    {"lmsSoundExpanded_startLoopingBeginEnd", 0},
    {"lmsSoundExpanded_stopAllSpriteSounds", 0},
    {"lmsSoundExpanded_stopLooping", 0},
    {"lmsSoundExpanded_stopSound", 0},
    {"lmsTempVars2_changeRuntimeVariable", 0},
    {"lmsTempVars2_changeThreadVariable", 0},
    {"lmsTempVars2_deleteAllRuntimeVariables", 0},
    {"lmsTempVars2_deleteRuntimeVariable", 0},
    {"lmsTempVars2_forEachThreadVariable", 0},
    {"lmsTempVars2_getRuntimeVariable", 1},
    {"lmsTempVars2_getThreadVariable", 1},
    {"lmsTempVars2_listRuntimeVariables", 1},
    {"lmsTempVars2_listThreadVariables", 1},
    {"lmsTempVars2_runtimeVariableExists", 2},
    {"lmsTempVars2_setRuntimeVariable", 0},
    {"lmsTempVars2_setThreadVariable", 0},
    {"lmsTempVars2_threadVariableExists", 2},
    {"lmsTempVars2_undefined", 0},
    {"lmsTempVars2_undefined", 0},
    {"lmsTimers_changeTimer", 0},
    {"lmsTimers_listExistingTimers", 1},
    {"lmsTimers_menu_operation", 1},
    {"lmsTimers_pauseTimer", 0},
    {"lmsTimers_removeTimer", 0},
    {"lmsTimers_removeTimers", 0},
    {"lmsTimers_resumeTimer", 0},
    {"lmsTimers_setTimer", 0},
    {"lmsTimers_startResetTimer", 0},
    {"lmsTimers_timerExists", 2},
    {"lmsTimers_valueOfTimer", 1},
    {"lmsTimers_whenTimerOp", 3},
    {"lmsVideo_deleteVideoURL", 0},
    {"lmsVideo_getAttribute", 1},
    {"lmsVideo_getCurrentVideo", 1},
    {"lmsVideo_getFrame", 1},
    {"lmsVideo_getLoadedVideos", 1},
    {"lmsVideo_getState", 2},
    {"lmsVideo_loadVideoURL", 0},
    {"lmsVideo_menu_attribute", 1},
    {"lmsVideo_menu_playbackType", 1},
    {"lmsVideo_menu_state", 1},
    {"lmsVideo_menu_targets", 1},
    {"lmsVideo_pause", 0},
    {"lmsVideo_resume", 0},
    {"lmsVideo_setPlaybackRate", 0},
    {"lmsVideo_setVolume", 0},
    {"lmsVideo_showVideo", 0},
    {"lmsVideo_startVideo", 0},
    {"lmsVideo_startVideoAndWait", 0},
    {"lmsVideo_stopShowingVideo", 0},
    {"lmsVideo_toggleLooping", 0},
    {"lmsVideo_undefined", 0},
    {"lmsclonesplus_cloneCount", 1},
    {"lmsclonesplus_cloneExists", 2},
    {"lmsclonesplus_createCloneOfMyselfWithVar", 0},
    {"lmsclonesplus_createCloneWithVar", 0},
    {"lmsclonesplus_deleteCloneWithVar", 0},
    {"lmsclonesplus_deleteClonesInSprite", 0},
    {"lmsclonesplus_getThingOfClone", 1},
    {"lmsclonesplus_getThingOfMainSprite", 1},
    {"lmsclonesplus_getVariableOfClone", 1},
    {"lmsclonesplus_getVariableOfMainSprite", 1},
    {"lmsclonesplus_isClone", 2},
    {"lmsclonesplus_menu_spriteMenu", 1},
    {"lmsclonesplus_menu_thingOfMenu", 1},
    {"lmsclonesplus_menu_variablesMenu", 1},
    {"lmsclonesplus_setVariableOfClone", 0},
    {"lmsclonesplus_setVariableOfMainSprite", 0},
    {"lmsclonesplus_spriteCloneCount", 1},
    {"lmsclonesplus_stopScriptsInClone", 0},
    {"lmsclonesplus_stopScriptsInMainSprite", 0},
    {"lmsclonesplus_stopScriptsInSprite", 0},
    {"lmsclonesplus_touchingCloneWithVar", 2},
    {"lmsclonesplus_touchingMainSprite", 2},
    {"lmsclonesplus_whenCloneStartsWithVar", 3},
    {"lmsutilsblocks_alertBlock", 0},
    {"lmsutilsblocks_angleReporter", 1},
    {"lmsutilsblocks_changeVariableBy", 0},
    {"lmsutilsblocks_clampNumber", 1},
    {"lmsutilsblocks_clearConsole", 0},
    {"lmsutilsblocks_clonesBeingUsed", 1},
    {"lmsutilsblocks_colourHex", 1},
    {"lmsutilsblocks_commentBool", 2},
    {"lmsutilsblocks_commentCommand", 0},
    {"lmsutilsblocks_commentHat", 3},
    {"lmsutilsblocks_commentString", 1},
    {"lmsutilsblocks_confirmationBlock", 2},
    {"lmsutilsblocks_consoleLog", 0},
    {"lmsutilsblocks_decodeFromBlock", 1},
    {"lmsutilsblocks_deleteAllVariables", 0},
    {"lmsutilsblocks_deleteVariable", 0},
    {"lmsutilsblocks_encodeToBlock", 1},
    {"lmsutilsblocks_equalsExactly", 2},
    {"lmsutilsblocks_exponentBlock", 1},
    {"lmsutilsblocks_findIndexOfString", 1},
    {"lmsutilsblocks_getEffectValue", 1},
    {"lmsutilsblocks_getVariable", 1},
    {"lmsutilsblocks_goToLink", 0},
    {"lmsutilsblocks_greenFlag", 0},
    {"lmsutilsblocks_inputPromptBlock", 1},
    {"lmsutilsblocks_isClone", 2},
    {"lmsutilsblocks_isUserMobile", 2},
    {"lmsutilsblocks_itemOfFromString", 1},
    {"lmsutilsblocks_keyStringPressed", 2},
    {"lmsutilsblocks_lessThanEqual", 2},
    {"lmsutilsblocks_lettersToOf", 1},
    {"lmsutilsblocks_listVariables", 1},
    {"lmsutilsblocks_matrixReporter", 1},
    {"lmsutilsblocks_menu_colorMenu", 1},
    {"lmsutilsblocks_menu_consoleLogMenu", 1},
    {"lmsutilsblocks_menu_conversionMenu", 1},
    {"lmsutilsblocks_menu_osBrowserMenu", 1},
    {"lmsutilsblocks_menu_screenReporterMenu", 1},
    {"lmsutilsblocks_menu_stringCheckMenu", 1},
    {"lmsutilsblocks_menu_trueFalseMenu", 1},
    {"lmsutilsblocks_moreThanEqual", 2},
    {"lmsutilsblocks_nandBoolean", 2},
    {"lmsutilsblocks_negativeReporter", 1},
    {"lmsutilsblocks_newlineCharacter", 1},
    {"lmsutilsblocks_norBoolean", 2},
    {"lmsutilsblocks_normaliseValue", 1},
    {"lmsutilsblocks_notEqualTo", 2},
    {"lmsutilsblocks_noteReporter", 1},
    {"lmsutilsblocks_osBrowserDetails", 1},
    {"lmsutilsblocks_projectURL", 1},
    {"lmsutilsblocks_readClipboard", 1},
    {"lmsutilsblocks_redirectToLink", 0},
    {"lmsutilsblocks_replaceWords", 1},
    {"lmsutilsblocks_reverseString", 1},
    {"lmsutilsblocks_rootBlock", 1},
    {"lmsutilsblocks_screenReporter", 1},
    {"lmsutilsblocks_setClipboard", 0},
    {"lmsutilsblocks_setSpriteSVG", 0},
    {"lmsutilsblocks_setUsername", 0},
    {"lmsutilsblocks_setVariableTo", 0},
    {"lmsutilsblocks_spriteClicked", 2},
    {"lmsutilsblocks_stringCheckBoolean", 2},
    {"lmsutilsblocks_stringIf", 1},
    {"lmsutilsblocks_stringIfElse", 1},
    {"lmsutilsblocks_stringReporter", 1},
    {"lmsutilsblocks_stringToLowerCase", 1},
    {"lmsutilsblocks_stringToUpperCase", 1},
    {"lmsutilsblocks_trueFalseBoolean", 2},
    {"lmsutilsblocks_undefined", 0},
    {"lmsutilsblocks_undefined", 0},
    {"lmsutilsblocks_whenBooleanHat", 3},
    {"lmsutilsblocks_whenKeyString", 3},
    {"lmsutilsblocks_windowReporter", 1},
    {"lmsutilsblocks_xnorBoolean", 2},
    {"lmsutilsblocks_xorBoolean", 2},
    {"localstorage_get", 1},
    {"localstorage_remove", 0},
    {"localstorage_removeAll", 0},
    {"localstorage_set", 0},
    {"localstorage_setProjectId", 0},
    {"localstorage_undefined", 0},
    {"localstorage_whenChanged", 0},
    {"mobilekeyboard0419_closeKeyboardBlock", 0},
    {"mobilekeyboard0419_getCursorPosition", 1},
    {"mobilekeyboard0419_getSelectionEnd", 1},
    {"mobilekeyboard0419_isAnySelected", 2},
    {"mobilekeyboard0419_isKeyboardOpen", 2},
    {"mobilekeyboard0419_menu_keyboardtypes", 1},
    {"mobilekeyboard0419_setCurrentValue", 0},
    {"mobilekeyboard0419_setCursorPosition", 0},
    {"mobilekeyboard0419_setDefaultValue", 0},
    {"mobilekeyboard0419_setSelectedText", 0},
    {"mobilekeyboard0419_showKeyboardAndWaitBlock", 0},
    {"mobilekeyboard0419_showKeyboardBlock", 0},
    {"mobilekeyboard0419_typedTextSinceKeyboardOpened", 1},
    {"mobilekeyboard0419_undefined", 0},
    {"notSound_play", 0},
    {"notSound_playUntilDone", 0},
    {"runtimeoptions_getCloneLimit", 1},
    {"runtimeoptions_getDimension", 1},
    {"runtimeoptions_getEnabled", 2},
    {"runtimeoptions_getFramerate", 1},
    {"runtimeoptions_greenFlag", 0},
    {"runtimeoptions_menu_changeable", 1},
    {"runtimeoptions_menu_clones", 1},
    {"runtimeoptions_menu_dimension", 1},
    {"runtimeoptions_menu_enabled", 1},
    {"runtimeoptions_menu_thing", 1},
    {"runtimeoptions_setCloneLimit", 0},
    {"runtimeoptions_setDimensions", 0},
    {"runtimeoptions_setEnabled", 0},
    {"runtimeoptions_setFramerate", 0},
    {"runtimeoptions_setUsername", 0},
    {"runtimeoptions_whenChange", 0},
    {"shovelColorPicker_getColor", 1},
    {"shovelColorPicker_getPos", 1},
    {"shovelColorPicker_menu_POSMenu", 1},
    {"shovelColorPicker_menu_RGBMenu", 1},
    {"shovelColorPicker_setColor", 0},
    {"shovelColorPicker_setPos", 0},
    {"shovelColorPicker_showPicker", 0},
    {"shovelColorPicker_whenChanged", 0},
    {"skyhigh173JSON_json_array_analysis", 1},
    {"skyhigh173JSON_json_array_concat", 1},
    {"skyhigh173JSON_json_array_create", 1},
    {"skyhigh173JSON_json_array_delete", 1},
    {"skyhigh173JSON_json_array_filter", 1},
    {"skyhigh173JSON_json_array_flat", 1},
    {"skyhigh173JSON_json_array_from", 1},
    {"skyhigh173JSON_json_array_fromto", 1},
    {"skyhigh173JSON_json_array_get", 1},
    {"skyhigh173JSON_json_array_insert", 1},
    {"skyhigh173JSON_json_array_itemH", 1},
    {"skyhigh173JSON_json_array_join", 1},
    {"skyhigh173JSON_json_array_push", 1},
    {"skyhigh173JSON_json_array_remove_all", 1},
    {"skyhigh173JSON_json_array_reverse", 1},
    {"skyhigh173JSON_json_array_set", 1},
    {"skyhigh173JSON_json_array_setlen", 1},
    {"skyhigh173JSON_json_array_sort", 1},
    {"skyhigh173JSON_json_delete", 1},
    {"skyhigh173JSON_json_equal", 2},
    {"skyhigh173JSON_json_get", 1},
    {"skyhigh173JSON_json_get_all", 1},
    {"skyhigh173JSON_json_has_key", 2},
    {"skyhigh173JSON_json_has_value", 2},
    {"skyhigh173JSON_json_is", 2},
    {"skyhigh173JSON_json_is_valid", 2},
    {"skyhigh173JSON_json_jlength", 1},
    {"skyhigh173JSON_json_length", 1},
    {"skyhigh173JSON_json_new", 1},
    {"skyhigh173JSON_json_set", 1},
    {"skyhigh173JSON_json_vm_getlist", 1},
    {"skyhigh173JSON_json_vm_setlist", 0},
    {"skyhigh173JSON_menu_analysis", 1},
    {"skyhigh173JSON_menu_equal", 1},
    {"skyhigh173JSON_menu_get_all", 1},
    {"skyhigh173JSON_menu_get_list", 1},
    {"skyhigh173JSON_menu_sort_order", 1},
    {"skyhigh173JSON_menu_types", 1},
    {"skyhigh173JSON_undefined", 0},
    {"skyhigh173JSON_undefined", 0},
    {"skyhigh173JSON_undefined", 0},
    {"skyhigh173JSON_undefined", 0},
    {"skyhigh173JSON_undefined", 0},
    {"stretch_changeStretch", 0},
    {"stretch_changeStretchX", 0},
    {"stretch_changeStretchY", 0},
    {"stretch_getX", 1},
    {"stretch_getY", 1},
    {"stretch_setStretch", 0},
    {"stretch_setStretchX", 0},
    {"stretch_setStretchY", 0},
    {"strings_count", 1},
    {"strings_countRegex", 1},
    {"strings_identical", 2},
    {"strings_indexof", 1},
    {"strings_isCase", 2},
    {"strings_letters_of", 1},
    {"strings_matchRegex", 1},
    {"strings_matchRegexJSON", 1},
    {"strings_menu_positions", 1},
    {"strings_menu_textCase", 1},
    {"strings_menu_trimMethod", 1},
    {"strings_posWith", 2},
    {"strings_repeat", 1},
    {"strings_replace", 1},
    {"strings_replaceRegex", 1},
    {"strings_reverse", 1},
    {"strings_split", 1},
    {"strings_testRegex", 2},
    {"strings_toCase", 1},
    {"strings_trim", 1},
    {"strings_unicodefrom", 1},
    {"strings_unicodeof", 1},
    {"text_addLine", 0},
    {"text_animateText", 0},
    {"text_animateTextInput", 0},
    {"text_animateUntilDone", 0},
    {"text_clearText", 0},
    {"text_getAnimateDuration", 1},
    {"text_getDisplayedText", 1},
    {"text_getLines", 1},
    {"text_getLinesV2", 1},
    {"text_getTextAttribute", 1},
    {"text_getTypeDelay", 1},
    {"text_isAnimating", 2},
    {"text_menu_align", 1},
    {"text_menu_animate", 1},
    {"text_menu_attribute", 1},
    {"text_menu_font", 1},
    {"text_menu_twAlign", 1},
    {"text_menu_twAnimate", 1},
    {"text_menu_twAnimateDuration", 1},
    {"text_menu_twFont", 1},
    {"text_menu_twWordWrap", 1},
    {"text_resetAnimateDuration", 0},
    {"text_resetTypeDelay", 0},
    {"text_resetWidth", 0},
    {"text_setAlignment", 0},
    {"text_setAnimateDuration", 0},
    {"text_setColor", 0},
    {"text_setFont", 0},
    {"text_setFontInput", 0},
    {"text_setOutlineColor", 0},
    {"text_setOutlineWidth", 0},
    {"text_setShakeIntensity", 0},
    {"text_setText", 0},
    {"text_setTypeDelay", 0},
    {"text_setWidth", 0},
    {"text_setWidthInput", 0},
    {"text_setWidthValue", 0},
    {"text_startAnimate", 0},
    {"text_textActive", 2},
    {"text_undefined", 0},
    {"text_undefined", 0},
    {"theshovelcanvaseffects_changeEffect", 0},
    {"theshovelcanvaseffects_cleareffects", 0},
    {"theshovelcanvaseffects_geteffect", 1},
    {"theshovelcanvaseffects_menu_EFFECTGETMENU", 1},
    {"theshovelcanvaseffects_menu_EFFECTMENU", 1},
    {"theshovelcanvaseffects_menu_RENDERMODE", 1},
    {"theshovelcanvaseffects_menu_borderTypes", 1},
    {"theshovelcanvaseffects_renderscale", 0},
    {"theshovelcanvaseffects_setBorder", 0},
    {"theshovelcanvaseffects_seteffect", 0},
    {"theshovelcanvaseffects_setrendermode", 0},
    {"tools_endl", 1},
    {"truefantombase_base_block", 1},
    {"truefantombase_is_base_block", 2},
    {"truefantombase_menu_base_menu", 1},
    {"truefantommath_almost_equal_block", 2},
    {"truefantommath_between", 2},
    {"truefantommath_between_or_equal", 2},
    {"truefantommath_clamp_block", 1},
    {"truefantommath_e_block", 1},
    {"truefantommath_exactly_cont_block", 2},
    {"truefantommath_exactly_equal_block", 2},
    {"truefantommath_exponent_block", 1},
    {"truefantommath_infinity_block", 1},
    {"truefantommath_is_float_block", 2},
    {"truefantommath_is_int_block", 2},
    {"truefantommath_is_multiple_of_block", 2},
    {"truefantommath_is_number_block", 2},
    {"truefantommath_is_safe_number_block", 2},
    {"truefantommath_less_or_equal_block", 2},
    {"truefantommath_log_with_base_block", 1},
    {"truefantommath_menu_OPERATOR", 1},
    {"truefantommath_more_or_equal_block", 2},
    {"truefantommath_nand_block", 2},
    {"truefantommath_negative_block", 1},
    {"truefantommath_nor_block", 2},
    {"truefantommath_not_almost_equal_block", 2},
    {"truefantommath_not_equal_block", 2},
    {"truefantommath_not_exactly_equal_block", 2},
    {"truefantommath_pi_block", 1},
    {"truefantommath_root_block", 1},
    {"truefantommath_scale_block", 1},
    {"truefantommath_sign_of", 1},
    {"truefantommath_true_math_op", 1},
    {"truefantommath_trunc2_block", 1},
    {"truefantommath_trunc_block", 1},
    {"truefantommath_xnor_block", 2},
    {"truefantommath_xor_block", 2},
    {"truefantomnetwork_browser_block", 1},
    {"truefantomnetwork_connected_to_internet_block", 2},
    {"truefantomnetwork_current_url_block", 1},
    {"truefantomnetwork_delete_block", 1},
    {"truefantomnetwork_downlink_max_speed_block", 1},
    {"truefantomnetwork_downlink_speed_block", 1},
    {"truefantomnetwork_get_block", 1},
    {"truefantomnetwork_menu_content_type", 1},
    {"truefantomnetwork_menu_default", 1},
    {"truefantomnetwork_menu_only_url_response_type", 1},
    {"truefantomnetwork_menu_response_type", 1},
    {"truefantomnetwork_network_generation_block", 1},
    {"truefantomnetwork_network_type_block", 1},
    {"truefantomnetwork_open_link_block", 0},
    {"truefantomnetwork_open_window_block", 0},
    {"truefantomnetwork_patch_block", 1},
    {"truefantomnetwork_post_block", 1},
    {"truefantomnetwork_put_block", 1},
    {"truefantomnetwork_redirect_link_block", 0},
    {"truefantomnetwork_rtt_block", 1},
    {"utilities_clamp", 1},
    {"utilities_currentMillisecond", 1},
    {"utilities_exponent", 1},
    {"utilities_falseBlock", 2},
    {"utilities_fetchFrom", 1},
    {"utilities_isExactly", 2},
    {"utilities_isLessOrEqual", 2},
    {"utilities_isMoreOrEqual", 2},
    {"utilities_letters", 1},
    {"utilities_newline", 1},
    {"utilities_parseJSON", 1},
    {"utilities_pi", 1},
    {"utilities_regexReplace", 1},
    {"utilities_stringToBoolean", 2},
    {"utilities_ternaryOperator", 1},
    {"utilities_trueBlock", 2},
    {"weatherPro_checkWeatherAlert", 2},
    {"weatherPro_getRemainingQuota", 1},
    {"weatherPro_getTemperature", 1},
    {"weatherPro_getWeather", 1},
    {"weatherPro_getWeatherCondition", 1},
    {"weatherPro_getWindSpeed", 1},
    {"weatherPro_setApiKey", 0},
    {"xeltallivclipblend_clearClipbox", 0},
    {"xeltallivclipblend_getAdditiveBlend", 2},
    {"xeltallivclipblend_getBlend", 1},
    {"xeltallivclipblend_getClipbox", 1},
    {"xeltallivclipblend_menu_blends", 1},
    {"xeltallivclipblend_menu_blends2", 1},
    {"xeltallivclipblend_menu_props", 1},
    {"xeltallivclipblend_menu_states", 1},
    {"xeltallivclipblend_setAdditiveBlend", 0},
    {"xeltallivclipblend_setBlend", 0},
    {"xeltallivclipblend_setBlend2", 0},
    {"xeltallivclipblend_setClipbox", 0},
    {"xeltallivclipblend_undefined", 0},
    {"yc6ncolormaster_adjustBrightness", 1},
    {"yc6ncolormaster_adjustSaturationFixed", 1},
    {"yc6ncolormaster_blendColors", 1},
    {"yc6ncolormaster_blendMultipleColors", 1},
    {"yc6ncolormaster_getHSLValues", 1},
    {"yc6ncolormaster_hexToRgbString", 1},
    {"yc6ncolormaster_hslToColor", 1},
    {"yc6ncolormaster_menu_COLOR_MENU", 1},
    {"yc6ncolormaster_nameToColor", 1},
    {"yc6ncolormaster_randomColor", 1},
    {"yc6ncolormaster_rgbToHex", 1},
    {"yc6ncolormaster_setTransparency", 1},
    {"yc6ncolormaster_testSaturationAdjustment", 1},
    {"yc6ncolormaster_verifyColor", 1},
    {"zx_calculateExpression", 1},
    {"zx_createTimer", 0},
    {"zx_daysInMonth", 1},
    {"zx_deleteTimer", 0},
    {"zx_generateRandomString", 1},
    {"zx_getCPUCores", 1},
    {"zx_getCPUName", 1},
    {"zx_getDayOfWeek", 1},
    {"zx_getGPUName", 1},
    {"zx_getRAM", 1},
    {"zx_getScreenResolution", 1},
    {"zx_getTimerValue", 1},
    {"zx_getWindowsVersion", 1},
    {"zx_insertText", 1},
    {"zx_isChinese", 2},
    {"zx_isEnglish", 2},
    {"zx_menu_mouseButtons", 1},
    {"zx_menu_timerUnits", 1},
    {"zx_pauseTimer", 0},
    {"zx_removeText", 1},
    {"zx_resetTimer", 0},
    {"zx_resumeTimer", 0},
    {"zx_reverseText", 1},
    {"zx_substring", 1},
    {"zx_toLowerCase", 1},
    {"zx_toUpperCase", 1},
    {"zx_waitHours", 0},
    {"zx_waitMinutes", 0},
    {"zx_whenMouseLongPress", 3},
};

inline const std::map<std::string, std::string> AUTO_EXT_NAMES = {
    {"Encoding", "Encoding"},
    {"MouseCursor", "Mouse Cursor"},
    {"SPcamera", "Camera V2"},
    {"WhenKeyPress", "Cyberexplorer's Toolbox Additional"},
    {"battery", "Battery"},
    {"clipboard", "Clipboard"},
    {"cubesterKeySimulation", "Key Simulation"},
    {"cubesterWindowControls", "Window Controls"},
    {"cyberexplorertoolboxmini", "Cyberexplorer's Toolbox Additional"},
    {"deepseekapi", "DeepSeek API"},
    {"files", "Files"},
    {"fullscreen0419", "Browser Fullscreen"},
    {"gaussianBlur", "高斯模糊"},
    {"iframe", "Iframe"},
    {"jeremygamerTweening", "Tweening"},
    {"lmsAssets", "Asset Manager"},
    {"lmsLooksPlus", "Looks+"},
    {"lmsSkins", "Skins"},
    {"lmsSoundExpanded", "Sound Expanded"},
    {"lmsTempVars2", "Temporary Variables"},
    {"lmsTimers", "More Timers"},
    {"lmsVideo", "Video"},
    {"lmsclonesplus", "Clones+"},
    {"lmsutilsblocks", "Lily's Toolbox"},
    {"localstorage", "Local Storage"},
    {"mobilekeyboard0419", "Mobile Keyboard"},
    {"notSound", "URL Playback"},
    {"runtimeoptions", "Runtime Options"},
    {"shovelColorPicker", "Color Picker"},
    {"skyhigh173JSON", "JSON"},
    {"stretch", "Stretch"},
    {"strings", "Text"},
    {"text", "Animated Text"},
    {"theshovelcanvaseffects", "Canvas Effects"},
    {"tools", "工具"},
    {"truefantombase", "Base"},
    {"truefantommath", "Math"},
    {"truefantomnetwork", "Network"},
    {"utilities", "Utilities"},
    {"weatherPro", "天气助手"},
    {"xeltallivclipblend", "Clipping & Blending"},
    {"yc6ncolormaster", "调色大师（精确版）"},
    {"zx", "zx小工具"},
};

} // namespace sb