// src/sb3_tables.hpp
// Scratch 2/3 积木翻译表（照抄 sb.py），与 sb1_tables.hpp 同样用 inline const。
#pragma once
#include <map>
#include <set>
#include <string>

namespace sb {

inline const std::map<std::string, std::string> SB2_T = {
    {"forward:", "移动 {__1} 步"},
    {"turnRight:", "右转 {__1} 度"},
    {"turnLeft:", "左转 {__1} 度"},
    {"heading:", "面向 {__1} 方向"},
    {"pointTowards:", "面向 {__1} 方向"},
    {"gotoX:y:", "移到 x: {__1} y: {__2}"},
    {"gotoSpriteOrMouse:", "移到 {__1}"},
    {"glideSecs:toX:y:elapsed:from:", "在 {__1} 秒内滑行到 x: {__2} y: {__3}"},
    {"changeXposBy:", "将 x 坐标增加 {__1}"},
    {"xpos:", "将 x 坐标设为 {__1}"},
    {"changeYposBy:", "将 y 坐标增加 {__1}"},
    {"ypos:", "将 y 坐标设为 {__1}"},
    {"bounceOffEdge", "碰到边缘就反弹"},
    {"setRotationStyle", "将旋转方式设为 {__1}"},
    {"xpos", "(x 坐标)"},
    {"ypos", "(y 坐标)"},
    {"heading", "(方向)"},
    {"say:", "说 {__1}"},
    {"say:forSecs:", "说 {__1} {__2} 秒"},
    {"say:duration:elapsed:from:", "说 {__1} {__2} 秒"},
    {"think:", "思考 {__1}"},
    {"think:forSecs:", "思考 {__1} {__2} 秒"},
    {"think:duration:elapsed:from:", "思考 {__1} {__2} 秒"},
    {"show", "显示"},
    {"hide", "隐藏"},
    {"lookLike:", "换成 {__1} 造型"},
    {"nextCostume", "下一个造型"},
    {"startScene", "换成 {__1} 背景"},
    {"nextScene", "下一个背景"},
    {"changeGraphicEffect:by:", "将 {__1} 特效增加 {__2}"},
    {"setGraphicEffect:to:", "将 {__1} 特效设为 {__2}"},
    {"filterReset", "清除图形特效"},
    {"changeSizeBy:", "将大小增加 {__1}"},
    {"setSizeTo:", "将大小设为 {__1}"},
    {"comeToFront", "移到最前面"},
    {"goToFront", "移到最前面"},
    {"goBackByLayers:", "后移 {__1} 层"},
    {"costumeIndex", "(造型编号)"},
    {"costumeName", "(造型名称)"},
    {"backgroundIndex", "(背景编号)"},
    {"sceneName", "(背景名称)"},
    {"scale", "(大小)"},
    {"playSound:", "播放声音 {__1}"},
    {"playSound:wait:", "播放声音 {__1} 等待播完"},
    {"doPlaySoundAndWait", "播放声音 {__1} 等待播完"},
    {"stopAllSounds", "停止所有声音"},
    {"changeVolumeBy:", "将音量增加 {__1}"},
    {"setVolumeTo:", "将音量设为 {__1}"},
    {"volume", "(音量)"},
    {"change Tempo by:", "将节奏增加 {__1}"},
    {"set Tempo to:", "将节奏设为 {__1}"},
    {"tempo", "(节奏)"},
    {"changeTempoBy:", "将节奏增加 {__1}"},
    {"setTempoTo:", "将节奏设为 {__1}"},
    {"drum:duration:elapsed:from:", "演奏鼓 {__1} {__2} 拍"},
    {"rest:elapsed:from:", "休止 {__1} 拍"},
    {"noteOn:duration:elapsed:from:", "演奏音符 {__1} {__2} 拍"},
    {"midiInstrument:", "将乐器设为 {__1}"},
    {"clearPenTrails", "清空画笔"},
    {"stampCostume", "图章"},
    {"putPenDown", "落笔"},
    {"putPenUp", "抬笔"},
    {"penColor:", "将笔的颜色设为 {__1}"},
    {"setPenHueTo:", "将笔的色相设为 {__1}"},
    {"changePenHueBy:", "将笔的色相增加 {__1}"},
    {"setPenShadeTo:", "将笔的明度设为 {__1}"},
    {"changePenShadeBy:", "将笔的明度增加 {__1}"},
    {"setPenSizeTo:", "将笔的粗细设为 {__1}"},
    {"penSize:", "将笔的粗细设为 {__1}"},
    {"changePenSizeBy:", "将笔的粗细增加 {__1}"},
    {"whenGreenFlag", "当 绿旗 被点击"},
    {"whenKeyPressed", "当按下 {__1} 键"},
    {"whenClicked", "当角色被点击"},
    {"whenSceneStarts", "当背景换成 {__1}"},
    {"whenSensorGreaterThan", "当 {__1} > {__2}"},
    {"whenIReceive", "当接收到 {__1}"},
    {"broadcast:", "广播 {__1}"},
    {"doBroadcastAndWait", "广播 {__1} 并等待"},
    {"whenCloned", "当作为克隆体启动时"},
    {"wait:elapsed:from:", "等待 {__1} 秒"},
    {"doRepeat", "重复执行 {__1} 次"},
    {"doForever", "重复执行"},
    {"doIf", "如果 {__1} 那么"},
    {"doIfElse", "如果 {__1} 那么"},
    {"doWaitUntil", "等待直到 {__1}"},
    {"doUntil", "重复执行直到 {__1}"},
    {"stopScripts", "停止 {__1}"},
    {"createCloneOf", "克隆 {__1}"},
    {"deleteClone", "删除此克隆体"},
    {"doAsk", "询问 {__1} 并等待"},
    {"answer", "(回答)"},
    {"keyPressed:", "按下 {__1} 键?"},
    {"mousePressed", "按下鼠标?"},
    {"mouseX", "(鼠标 x 坐标)"},
    {"mouseY", "(鼠标 y 坐标)"},
    {"soundLevel", "(响度)"},
    {"timer", "(计时器)"},
    {"timerReset", "计时器归零"},
    {"distanceTo:", "到 {__1} 的距离"},
    {"touching:", "碰到 {__1}?"},
    {"touchingColor:", "碰到颜色 {__1}?"},
    {"color:sees:", "颜色 {__1} 碰到 {__2}?"},
    {"getAttribute:of:", "{__2} 的 {__1}"},
    {"timeAndDate", "当前{__1}"},
    {"timestamp", "(2000 年以来的天数)"},
    {"getUserName", "(用户名)"},
    {"+", "({__1} + {__2})"},
    {"-", "({__1} - {__2})"},
    {"*", "({__1} × {__2})"},
    {"/", "({__1} ÷ {__2})"},
    {"%", "({__1} 除以 {__2} 的余数)"},
    {"randomFrom:to:", "在 {__1} 到 {__2} 之间取随机数"},
    {">", "({__1} > {__2})"},
    {"<", "({__1} < {__2})"},
    {"=", "({__1} = {__2})"},
    {"&", "({__1} 且 {__2})"},
    {"|", "({__1} 或 {__2})"},
    {"not", "(不成立 {__1})"},
    {"concatenate:with:", "(连接 {__1} 和 {__2})"},
    {"letter:of:", "({__2} 的第 {__1} 个字符)"},
    {"stringLength:", "({__1} 的字符数)"},
    {"contains:", "({__1} 包含 {__2}?)"},
    {"rounded", "(将 {__1} 四舍五入)"},
    {"compute", "({__2} 的 {__1})"},
    {"computeFunction:of:", "({__2} 的 {__1})"},
    {"readVariable", "{__1}"},
    {"setVar:to:", "将 {__1} 设为 {__2}"},
    {"changeVar:by:", "将 {__1} 增加 {__2}"},
    {"showVariable:", "显示变量 {__1}"},
    {"hideVariable:", "隐藏变量 {__1}"},
    {"contentsOfList:", "{__1}"},
    {"append:toList:", "将 {__1} 加入 {__2}"},
    {"deleteLine:ofList:", "删除 {__2} 的第 {__1} 项"},
    {"insert:at:ofList:", "将 {__1} 插入 {__2} 的第 {__3} 项"},
    {"setLine:ofList:to:", "将 {__2} 的第 {__1} 项替换为 {__3}"},
    {"getLine:ofList:", "{__2} 的第 {__1} 项"},
    {"lineCountOfList:", "{__1} 的项目数"},
    {"list:contains:", "{__1} 包含 {__2}?"},
    {"showList:", "显示列表 {__1}"},
    {"hideList:", "隐藏列表 {__1}"},
    {"getParam", "{__1}"},
};

inline const std::map<std::string, std::string> SB2_MENU = {
    {"mouse-pointer", "鼠标指针"}, {"_mouse_", "鼠标指针"}, {"_edge_", "边缘"},
    {"_random_", "随机位置"}, {"myself", "自己"}, {"left-right", "左右翻转"},
    {"don't rotate", "不旋转"}, {"normal", "任意旋转"},
    {"color", "颜色"}, {"fisheye", "鱼眼"}, {"whirl", "漩涡"}, {"pixelate", "像素化"},
    {"mosaic", "马赛克"}, {"brightness", "亮度"}, {"ghost", "虚像"},
    {"all", "全部脚本"}, {"this script", "这个脚本"},
    {"other scripts in sprite", "该角色的其他脚本"},
    {"year", "年"}, {"month", "月"}, {"date", "日"}, {"day", "星期"},
    {"hour", "时"}, {"minute", "分"}, {"second", "秒"},
    {"x position", "x 坐标"}, {"y position", "y 坐标"}, {"direction", "方向"},
    {"costume #", "造型编号"}, {"costume name", "造型名称"}, {"size", "大小"},
    {"volume", "音量"}, {"loudness", "响度"}, {"timer", "计时器"},
    {"space", "空格"}, {"up arrow", "↑"}, {"down arrow", "↓"},
    {"right arrow", "→"}, {"left arrow", "←"}, {"any", "任意"}, {"enter", "回车"},
    {"abs", "绝对值"}, {"floor", "向下取整"}, {"ceiling", "向上取整"}, {"sqrt", "平方根"},
    {"sin", "正弦"}, {"cos", "余弦"}, {"tan", "正切"}, {"asin", "反正弦"},
    {"acos", "反余弦"}, {"atan", "反正切"}, {"ln", "ln"}, {"log", "log"},
    {"e ^", "e 的次方"}, {"10 ^", "10 的次方"},
};

inline const std::map<std::string, std::string> SB3_T = {
    {"motion_movesteps", "移动 {STEPS} 步"},
    {"motion_turnright", "右转 {DEGREES} 度"},
    {"motion_turnleft", "左转 {DEGREES} 度"},
    {"motion_goto", "移到 {TO}"},
    {"motion_gotoxy", "移到 x: {X} y: {Y}"},
    {"motion_glideto", "在 {SECS} 秒内滑行到 {TO}"},
    {"motion_glidesecstoxy", "在 {SECS} 秒内滑行到 x: {X} y: {Y}"},
    {"motion_pointindirection", "面向 {DIRECTION} 方向"},
    {"motion_pointtowards", "面向 {TOWARDS} 方向"},
    {"motion_changexby", "将 x 坐标增加 {DX}"},
    {"motion_setx", "将 x 坐标设为 {X}"},
    {"motion_changeyby", "将 y 坐标增加 {DY}"},
    {"motion_sety", "将 y 坐标设为 {Y}"},
    {"motion_ifonedgebounce", "碰到边缘就反弹"},
    {"motion_setrotationstyle", "将旋转方式设为 {STYLE}"},
    {"motion_xposition", "(x 坐标)"},
    {"motion_yposition", "(y 坐标)"},
    {"motion_direction", "(方向)"},
    {"looks_sayforsecs", "说 {MESSAGE} {SECS} 秒"},
    {"looks_say", "说 {MESSAGE}"},
    {"looks_thinkforsecs", "思考 {MESSAGE} {SECS} 秒"},
    {"looks_think", "思考 {MESSAGE}"},
    {"looks_switchcostumeto", "换成 {COSTUME} 造型"},
    {"looks_nextcostume", "下一个造型"},
    {"looks_switchbackdropto", "换成 {BACKDROP} 背景"},
    {"looks_nextbackdrop", "下一个背景"},
    {"looks_changesizeby", "将大小增加 {CHANGE}"},
    {"looks_setsizeto", "将大小设为 {SIZE}"},
    {"looks_changeeffectby", "将 {EFFECT} 特效增加 {CHANGE}"},
    {"looks_seteffectto", "将 {EFFECT} 特效设为 {VALUE}"},
    {"looks_cleargraphiceffects", "清除图形特效"},
    {"looks_show", "显示"},
    {"looks_hide", "隐藏"},
    {"looks_gotofrontback", "移到{FRONT_BACK}"},
    {"looks_goforwardbackwardlayers", "{FORWARD_BACKWARD} {NUM} 层"},
    {"looks_costumenumbername", "造型{NUMBER_NAME}"},
    {"looks_backdropnumbername", "背景{NUMBER_NAME}"},
    {"looks_size", "(大小)"},
    {"sound_play", "播放声音 {SOUND_MENU}"},
    {"sound_playuntildone", "播放声音 {SOUND_MENU} 等待播完"},
    {"sound_stopallsounds", "停止所有声音"},
    {"sound_changeeffectby", "将 {EFFECT} 音效增加 {VALUE}"},
    {"sound_seteffectto", "将 {EFFECT} 音效设为 {VALUE}"},
    {"sound_cleareffects", "清除音效"},
    {"sound_changevolumeby", "将音量增加 {VOLUME}"},
    {"sound_setvolumeto", "将音量设为 {VOLUME}"},
    {"sound_volume", "(音量)"},
    {"event_whenflagclicked", "当 绿旗 被点击"},
    {"event_whenkeypressed", "当按下 {KEY_OPTION} 键"},
    {"event_whenthisspriteclicked", "当角色被点击"},
    {"event_whenstageclicked", "当舞台被点击"},
    {"event_whenbackdropswitchesto", "当背景换成 {BACKDROP}"},
    {"event_whengreaterthan", "当 {WHENGREATERTHANMENU} > {VALUE}"},
    {"event_whenbroadcastreceived", "当接收到 {BROADCAST_OPTION}"},
    {"event_whencloned", "当作为克隆体启动时"},
    {"event_broadcast", "广播 {BROADCAST_INPUT}"},
    {"event_broadcastandwait", "广播 {BROADCAST_INPUT} 并等待"},
    {"control_wait", "等待 {DURATION} 秒"},
    {"control_repeat", "重复执行 {TIMES} 次"},
    {"control_forever", "重复执行"},
    {"control_if", "如果 {CONDITION} 那么"},
    {"control_if_else", "如果 {CONDITION} 那么"},
    {"control_wait_until", "等待直到 {CONDITION}"},
    {"control_repeat_until", "重复执行直到 {CONDITION}"},
    {"control_while", "当 {CONDITION} 重复执行"},
    {"control_for_each", "对于 {VARIABLE} 中的每个 {VALUE}"},
    {"control_stop", "停止 {STOP_OPTION}"},
    {"control_start_as_clone", "当作为克隆体启动时"},
    {"control_create_clone_of", "克隆 {CLONE_OPTION}"},
    {"control_delete_this_clone", "删除此克隆体"},
    {"sensing_touchingobject", "碰到 {TOUCHINGOBJECTMENU}?"},
    {"sensing_touchingcolor", "碰到颜色 {COLOR}?"},
    {"sensing_coloristouchingcolor", "颜色 {COLOR} 碰到 {COLOR2}?"},
    {"sensing_distanceto", "到 {DISTANCETOMENU} 的距离"},
    {"sensing_askandwait", "询问 {QUESTION} 并等待"},
    {"sensing_answer", "(回答)"},
    {"sensing_keypressed", "按下 {KEY_OPTION} 键?"},
    {"sensing_mousedown", "按下鼠标?"},
    {"sensing_mousex", "(鼠标 x 坐标)"},
    {"sensing_mousey", "(鼠标 y 坐标)"},
    {"sensing_loudness", "(响度)"},
    {"sensing_timer", "(计时器)"},
    {"sensing_resettimer", "计时器归零"},
    {"sensing_of", "{OBJECT} 的 {PROPERTY}"},
    {"sensing_current", "当前{CURRENTMENU}"},
    {"sensing_dayssince2000", "(2000 年以来的天数)"},
    {"sensing_username", "(用户名)"},
    {"sensing_setdragmode", "将拖动模式设为 {DRAG_MODE}"},
    {"operator_add", "({NUM1} + {NUM2})"},
    {"operator_subtract", "({NUM1} - {NUM2})"},
    {"operator_multiply", "({NUM1} × {NUM2})"},
    {"operator_divide", "({NUM1} ÷ {NUM2})"},
    {"operator_random", "在 {FROM} 到 {TO} 之间取随机数"},
    {"operator_gt", "({OPERAND1} > {OPERAND2})"},
    {"operator_lt", "({OPERAND1} < {OPERAND2})"},
    {"operator_equals", "({OPERAND1} = {OPERAND2})"},
    {"operator_and", "({OPERAND1} 且 {OPERAND2})"},
    {"operator_or", "({OPERAND1} 或 {OPERAND2})"},
    {"operator_not", "(不成立 {OPERAND})"},
    {"operator_join", "(连接 {STRING1} 和 {STRING2})"},
    {"operator_letter_of", "({STRING} 的第 {LETTER} 个字符)"},
    {"operator_length", "({STRING} 的字符数)"},
    {"operator_contains", "({STRING1} 包含 {STRING2}?)"},
    {"operator_mod", "({NUM1} 除以 {NUM2} 的余数)"},
    {"operator_round", "(将 {NUM} 四舍五入)"},
    {"operator_mathop", "({NUM} 的 {OPERATOR})"},
    {"data_variable", "{VARIABLE}"},
    {"data_setvariableto", "将 {VARIABLE} 设为 {VALUE}"},
    {"data_changevariableby", "将 {VARIABLE} 增加 {VALUE}"},
    {"data_showvariable", "显示变量 {VARIABLE}"},
    {"data_hidevariable", "隐藏变量 {VARIABLE}"},
    {"data_listcontents", "{LIST}"},
    {"data_addtolist", "将 {ITEM} 加入 {LIST}"},
    {"data_deleteoflist", "删除 {LIST} 的第 {INDEX} 项"},
    {"data_deletealloflist", "删除 {LIST} 的全部项目"},
    {"data_insertatlist", "将 {ITEM} 插入 {LIST} 的第 {INDEX} 项"},
    {"data_replaceitemoflist", "将 {LIST} 的第 {INDEX} 项替换为 {ITEM}"},
    {"data_itemoflist", "{LIST} 的第 {INDEX} 项"},
    {"data_itemnumoflist", "{ITEM} 在 {LIST} 中的编号"},
    {"data_lengthoflist", "{LIST} 的项目数"},
    {"data_listcontainsitem", "{LIST} 包含 {ITEM}?"},
    {"data_showlist", "显示列表 {LIST}"},
    {"data_hidelist", "隐藏列表 {LIST}"},
    {"argument_reporter_string_number", "{VALUE}"},
    {"argument_reporter_boolean", "{VALUE}"},
    {"sound_sounds_menu", "{SOUND_MENU}"},
    {"looks_costume", "{COSTUME}"},
    {"looks_backdrops", "{BACKDROP}"},
    {"motion_goto_menu", "{TO}"},
    {"motion_glideto_menu", "{TO}"},
    {"motion_pointtowards_menu", "{TOWARDS}"},
    {"sensing_touchingobjectmenu", "{TOUCHINGOBJECTMENU}"},
    {"sensing_distancetomenu", "{DISTANCETOMENU}"},
    {"sensing_keyoptions", "{KEY_OPTION}"},
    {"sensing_of_object_menu", "{OBJECT}"},
    {"control_create_clone_of_menu", "{CLONE_OPTION}"},
    {"event_broadcast_menu", "{BROADCAST_OPTION}"},
    {"pen_clear", "清空画笔"},
    {"pen_stamp", "图章"},
    {"pen_penDown", "落笔"},
    {"pen_penUp", "抬笔"},
    {"pen_setPenColorToColor", "将笔的颜色设为 {COLOR}"},
    {"pen_changePenColorParamBy", "将笔的 {COLOR_PARAM} 增加 {VALUE}"},
    {"pen_setPenColorParamTo", "将笔的 {COLOR_PARAM} 设为 {VALUE}"},
    {"pen_menu_colorParam", "{COLOR_PARAM}"},
    {"pen_changePenSizeBy", "将笔的粗细增加 {SIZE}"},
    {"pen_setPenSizeTo", "将笔的粗细设为 {SIZE}"},
    {"pen_setPenShadeToNumber", "将笔的色相设为 {SHADE}"},
    {"pen_changePenShadeBy", "将笔的色相增加 {SHADE}"},
};

inline const std::map<std::string, std::map<std::string, std::string>> FIELD_MAP = {
    {"EFFECT", {{"COLOR","颜色"},{"FISHEYE","鱼眼"},{"WHIRL","漩涡"},
                {"PIXELATE","像素化"},{"MOSAIC","马赛克"},{"BRIGHTNESS","亮度"},
                {"GHOST","虚像"}}},
    {"STYLE",  {{"left-right","左右翻转"},{"don't rotate","不旋转"},
                {"all around","任意旋转"}}},
    {"FRONT_BACK", {{"front","最前面"},{"back","最后面"}}},
    {"FORWARD_BACKWARD", {{"forward","前移"},{"backward","后移"}}},
    {"NUMBER_NAME", {{"number","编号"},{"name","名称"}}},
    {"COLOR_PARAM", {{"color","颜色"},{"brightness","亮度"},{"saturation","饱和度"}}},
    {"STOP_OPTION", {{"all","全部脚本"},{"this script","这个脚本"},
                     {"other scripts in sprite","该角色的其他脚本"},
                     {"other scripts in stage","舞台的其他脚本"}}},
    {"CURRENTMENU", {{"YEAR","年"},{"MONTH","月"},{"DATE","日"},{"DAY","星期"},
                     {"HOUR","时"},{"MINUTE","分"},{"SECOND","秒"}}},
    {"PROPERTY", {{"x position","x 坐标"},{"y position","y 坐标"},{"direction","方向"},
                  {"costume #","造型编号"},{"costume name","造型名称"},{"size","大小"},
                  {"volume","音量"},{"position","位置"},{"backdrop #","背景编号"},
                  {"backdrop name","背景名称"}}},
    {"OPERATOR", {{"abs","绝对值"},{"floor","向下取整"},{"ceiling","向上取整"},{"sqrt","平方根"},
                  {"sin","正弦"},{"cos","余弦"},{"tan","正切"},{"asin","反正弦"},
                  {"acos","反余弦"},{"atan","反正切"},{"ln","ln"},{"log","log"},
                  {"e ^","e 的次方"},{"10 ^","10 的次方"}}},
    {"SOUND_EFFECT", {{"PITCH","音高"},{"PAN","左右平衡"}}},
    {"KEY_OPTION", {{"space","空格"},{"up arrow","↑"},{"down arrow","↓"},
                    {"right arrow","→"},{"left arrow","←"},{"any","任意"},{"enter","回车"}}},
    {"WHENGREATERTHANMENU", {{"LOUDNESS","响度"},{"TIMER","计时器"}}},
    {"BROADCAST_OPTION", {}},
};

// 哪些 SB2 opcode 的第几个输入是菜单（SB2_MENU_POS）
inline const std::map<std::string, std::set<int>> SB2_MENU_POS_MAP = {
    {"pointTowards:", {1}}, {"gotoSpriteOrMouse:", {1}}, {"setRotationStyle", {1}},
    {"changeGraphicEffect:by:", {1}}, {"setGraphicEffect:to:", {1}},
    {"whenKeyPressed", {1}}, {"keyPressed:", {1}}, {"touching:", {1}},
    {"distanceTo:", {1}}, {"getAttribute:of:", {1}}, {"timeAndDate", {1}},
    {"stopScripts", {1}}, {"createCloneOf", {1}}, {"whenSensorGreaterThan", {1}},
    {"compute", {1}}, {"computeFunction:of:", {1}},
};

} // namespace sb